// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package main

import (
	"crypto/rand"
	"crypto/rsa"
	"crypto/x509"
	"crypto/x509/pkix"
	"encoding/json"
	"encoding/pem"
	"errors"
	"flag"
	"fmt"
	"github.com/awcullen/opcua/server"
	"github.com/awcullen/opcua/ua"
	"github.com/charmbracelet/bubbletea"
	"github.com/charmbracelet/lipgloss"
	"math"
	"math/big"
	"net"
	"net/url"
	"os"
	"path/filepath"
	"plc-autogen/runtime"
	"reflect"
	"sort"
	"strings"
	"sync"
	"time"
	"unsafe"
)

type memoryTag struct {
	Name                string
	GeneratedName       string
	NodeID              string
	BrowseName          string
	AliasNodeIDs        []string
	Index               []int
	TypeRef             string
	Section             string
	Structured          bool
	BrowseObject        bool
	Writable            bool
	Parents             []opcuaBrowseParent
	ParentNodeID        string
	ParentReferenceKind string
}

type opcuaBrowseParent struct {
	NodeID        string
	BrowseName    string
	DisplayName   string
	ParentNodeID  string
	ReferenceKind string
}

type sharedMemory struct {
	mu      sync.RWMutex
	mem     plcruntime.Memory
	runtime *runtimeState
}

func (s *sharedMemory) Set(mem plcruntime.Memory) {
	s.mu.Lock()
	s.mem = mem
	s.mu.Unlock()
}

func (s *sharedMemory) AttachRuntime(state *runtimeState) {
	if s == nil {
		return
	}
	s.runtime = state
}

func (s *sharedMemory) runtimeState() *runtimeState {
	if s == nil {
		return nil
	}
	return s.runtime
}

func (s *sharedMemory) Snapshot() plcruntime.Memory {
	if rt := s.runtimeState(); rt != nil {
		return rt.MemorySnapshot()
	}
	s.mu.RLock()
	defer s.mu.RUnlock()
	return s.mem
}

func (s *sharedMemory) SnapshotAndResetCycleWindow() plcruntime.Memory {
	if rt := s.runtimeState(); rt != nil {
		return rt.MemorySnapshotAndResetCycleWindow()
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	mem := s.mem
	s.mem.SCLH_CycleWindowNS = 0
	s.mem.SCLH_CycleWindowCount = 0
	return mem
}

func (s *sharedMemory) Write(index []int, value any) (any, ua.StatusCode) {
	if s == nil || len(index) == 0 {
		return nil, ua.BadNodeIDUnknown
	}
	if rt := s.runtimeState(); rt != nil {
		if status := rt.WriteMemoryValue(index, value); status.IsBad() {
			return nil, status
		}
		return readOPCUATagValueAt(s, index), ua.Good
	}
	s.mu.Lock()
	defer s.mu.Unlock()
	target := reflect.ValueOf(&s.mem).Elem().FieldByIndex(index)
	if status := setReflectValue(target, value); status.IsBad() {
		return nil, status
	}
	return readReflectValue(target), ua.Good
}

const (
	opcuaDINamespaceURI          = "http://opcfoundation.org/UA/DI/"
	opcuaSiemensNamespaceURI     = "http://www.siemens.com/simatic-s7-opcua"
	opcuaRootNodeID              = "PLC"
	opcuaRootBrowseName          = "MotorExamplePLC"
	opcuaSimaticDeviceTypeID     = 1002
	opcuaFunctionalGroupTypeID   = 1005
	opcuaDebugFolderID           = "PLC.Debug"
	opcuaSnapshotsFolderID       = "PLC.Debug.Snapshots"
	opcuaDefaultHostName         = "127.0.0.1"
	opcuaMinimumSamplingInterval = -1.0
)

const runtimeHasDebugSnapshotOPC = false

func opcuaWritableRolePermissions() []ua.RolePermissionType {
	permissions := ua.PermissionTypeBrowse | ua.PermissionTypeRead | ua.PermissionTypeWrite | ua.PermissionTypeReadHistory
	return []ua.RolePermissionType{
		{RoleID: ua.ObjectIDWellKnownRoleAnonymous, Permissions: permissions},
		{RoleID: ua.ObjectIDWellKnownRoleAuthenticatedUser, Permissions: permissions},
	}
}

func opcuaAcceptUserNameIdentity(userIdentity ua.UserNameIdentity, applicationURI string, endpointURL string) error {
	return nil
}

func opcuaApplicationURI() string {
	return "urn:SIMATIC.S7-1500.OPC-UA.Application:" + opcuaRootBrowseName
}

func opcuaRootFunctionalGroupNames() []string {
	return []string{"Counters", "DataBlocksGlobal", "DataBlocksInstance", "Inputs", "Memory", "Outputs", "Timers"}
}

type opcuaServer struct {
	srv       *server.Server
	endpoint  string
	done      chan error
	cleanup   func()
	closeOnce sync.Once
}

func (s *opcuaServer) EndpointURL() string {
	if s == nil {
		return ""
	}
	return s.endpoint
}

func (s *opcuaServer) Close() error {
	if s == nil {
		return nil
	}
	var closeErr error
	s.closeOnce.Do(func() {
		if s.srv != nil {
			closeErr = s.srv.Close()
		}
		if s.done != nil {
			<-s.done
		}
		if s.cleanup != nil {
			s.cleanup()
		}
	})
	return closeErr
}

func startOPCUAServer(snapshot *sharedMemory, tags []memoryTag, debugSnapshots *debugSnapshotStore, port int, advertisedHost string) (*opcuaServer, error) {
	if port <= 0 {
		return nil, nil
	}
	advertisedHost = strings.TrimSpace(advertisedHost)
	if advertisedHost == "" {
		advertisedHost = opcuaDefaultHostName
	}

	appURI := opcuaApplicationURI()
	certPath, keyPath, cleanup, err := writeOPCUASelfSignedCert(advertisedHost, appURI)
	if err != nil {
		return nil, err
	}

	endpoint := opcuaEndpointURL(advertisedHost, port)
	appName := opcuaRootBrowseName
	app := ua.ApplicationDescription{
		ApplicationURI:      appURI,
		ProductURI:          "urn:plc-run",
		ApplicationName:     ua.LocalizedText{Text: appName, Locale: "en"},
		ApplicationType:     ua.ApplicationTypeServer,
		DiscoveryProfileURI: "",
		DiscoveryURLs:       []string{endpoint},
	}

	srv, err := server.New(
		app,
		certPath,
		keyPath,
		endpoint,
		server.WithAnonymousIdentity(true),
		server.WithAuthenticateUserNameIdentityFunc(opcuaAcceptUserNameIdentity),
		server.WithSecurityPolicyNone(true),
		server.WithInsecureSkipVerify(),
		server.WithServerDiagnostics(false),
	)
	if err != nil {
		cleanup()
		return nil, err
	}
	if err := installOPCUANodes(srv, snapshot, tags, debugSnapshots); err != nil {
		_ = srv.Close()
		cleanup()
		return nil, err
	}

	state := &opcuaServer{
		srv:      srv,
		endpoint: endpoint,
		done:     make(chan error, 1),
		cleanup:  cleanup,
	}
	go func() {
		err := srv.ListenAndServe()
		if err != nil && !errors.Is(err, ua.BadServerHalted) {
			state.done <- err
			return
		}
		state.done <- nil
	}()
	if err := waitForTCPReady(port, endpoint, 8*time.Second); err != nil {
		_ = state.Close()
		return nil, err
	}
	return state, nil
}

func waitForTCPReady(port int, endpoint string, timeout time.Duration) error {
	addr := fmt.Sprintf("127.0.0.1:%d", port)
	deadline := time.Now().Add(timeout)
	for time.Now().Before(deadline) {
		conn, err := net.DialTimeout("tcp", addr, 100*time.Millisecond)
		if err == nil {
			_ = conn.Close()
			return nil
		}
		time.Sleep(50 * time.Millisecond)
	}
	return fmt.Errorf("timeout waiting for OPC-UA listener at %s", endpoint)
}

func opcuaEndpointURL(advertisedHost string, port int) string {
	return "opc.tcp://" + net.JoinHostPort(opcuaNormalizeAdvertisedHost(advertisedHost), fmt.Sprint(port))
}

func opcuaNormalizeAdvertisedHost(host string) string {
	host = strings.TrimSpace(host)
	if strings.HasPrefix(host, "[") && strings.HasSuffix(host, "]") {
		host = strings.TrimPrefix(strings.TrimSuffix(host, "]"), "[")
	}
	return host
}

func opcuaCertificateHostSANs(advertisedHost string) ([]string, []net.IP) {
	dnsNames := []string{"localhost"}
	ipAddresses := []net.IP{net.ParseIP("127.0.0.1")}
	host := opcuaNormalizeAdvertisedHost(advertisedHost)
	if host == "" {
		return dnsNames, ipAddresses
	}
	if ip := net.ParseIP(host); ip != nil {
		for _, existing := range ipAddresses {
			if existing != nil && existing.Equal(ip) {
				return dnsNames, ipAddresses
			}
		}
		return dnsNames, append(ipAddresses, ip)
	}
	for _, existing := range dnsNames {
		if strings.EqualFold(existing, host) {
			return dnsNames, ipAddresses
		}
	}
	return append(dnsNames, host), ipAddresses
}

func writeOPCUASelfSignedCert(advertisedHost string, applicationURI string) (certPath string, keyPath string, cleanup func(), err error) {
	tmpDir, err := os.MkdirTemp("", "plc-run-opcua-*")
	if err != nil {
		return "", "", nil, err
	}
	cleanup = func() {
		_ = os.RemoveAll(tmpDir)
	}

	priv, err := rsa.GenerateKey(rand.Reader, 2048)
	if err != nil {
		cleanup()
		return "", "", nil, err
	}
	now := time.Now().UTC()
	dnsNames, ipAddresses := opcuaCertificateHostSANs(advertisedHost)
	var uriSANs []*url.URL
	if strings.TrimSpace(applicationURI) != "" {
		uri, err := url.Parse(strings.TrimSpace(applicationURI))
		if err != nil {
			cleanup()
			return "", "", nil, err
		}
		uriSANs = append(uriSANs, uri)
	}
	tpl := &x509.Certificate{
		SerialNumber:          big.NewInt(now.UnixNano()),
		Subject:               pkix.Name{CommonName: "plc-run-opcua"},
		NotBefore:             now.Add(-time.Hour),
		NotAfter:              now.Add(24 * time.Hour),
		KeyUsage:              x509.KeyUsageDigitalSignature | x509.KeyUsageKeyEncipherment | x509.KeyUsageCertSign,
		ExtKeyUsage:           []x509.ExtKeyUsage{x509.ExtKeyUsageServerAuth},
		BasicConstraintsValid: true,
		IsCA:                  true,
		DNSNames:              dnsNames,
		IPAddresses:           ipAddresses,
		URIs:                  uriSANs,
	}
	der, err := x509.CreateCertificate(rand.Reader, tpl, tpl, &priv.PublicKey, priv)
	if err != nil {
		cleanup()
		return "", "", nil, err
	}

	certPath = filepath.Join(tmpDir, "server.crt")
	keyPath = filepath.Join(tmpDir, "server.key")
	certPEM := pem.EncodeToMemory(&pem.Block{Type: "CERTIFICATE", Bytes: der})
	keyPEM := pem.EncodeToMemory(&pem.Block{Type: "RSA PRIVATE KEY", Bytes: x509.MarshalPKCS1PrivateKey(priv)})
	if err := os.WriteFile(certPath, certPEM, 0o600); err != nil {
		cleanup()
		return "", "", nil, err
	}
	if err := os.WriteFile(keyPath, keyPEM, 0o600); err != nil {
		cleanup()
		return "", "", nil, err
	}
	return certPath, keyPath, cleanup, nil
}

func installOPCUANodes(srv *server.Server, snapshot *sharedMemory, tags []memoryTag, debugSnapshots *debugSnapshotStore) error {
	nm := srv.NamespaceManager()
	diNS := nm.Add(opcuaDINamespaceURI)
	ns := nm.Add(opcuaSiemensNamespaceURI)
	rootID := ua.NewNodeIDString(ns, opcuaRootNodeID)
	simaticDeviceTypeID := ua.NewNodeIDNumeric(ns, opcuaSimaticDeviceTypeID)
	functionalGroupTypeID := ua.NewNodeIDNumeric(diNS, opcuaFunctionalGroupTypeID)
	hasInputVarID := ua.NewNodeIDNumeric(ns, 4003)
	hasOutputVarID := ua.NewNodeIDNumeric(ns, 4004)
	hasLocalVarID := ua.NewNodeIDNumeric(ns, 4005)

	root := server.NewObjectNode(
		srv,
		rootID,
		ua.NewQualifiedName(ns, opcuaRootBrowseName),
		ua.LocalizedText{Text: opcuaRootBrowseName},
		ua.LocalizedText{Text: opcuaRootBrowseName},
		nil,
		[]ua.Reference{
			{ReferenceTypeID: ua.ReferenceTypeIDOrganizes, IsInverse: true, TargetID: ua.NewExpandedNodeID(ua.ObjectIDObjectsFolder)},
			{ReferenceTypeID: ua.ReferenceTypeIDHasTypeDefinition, IsInverse: false, TargetID: ua.NewExpandedNodeID(simaticDeviceTypeID)},
		},
		0,
	)

	nodes := []server.Node{
		server.NewObjectTypeNode(
			srv,
			simaticDeviceTypeID,
			ua.NewQualifiedName(ns, "SimaticDeviceType"),
			ua.LocalizedText{Text: "SimaticDeviceType"},
			ua.LocalizedText{Text: "SimaticDeviceType"},
			nil,
			[]ua.Reference{{ReferenceTypeID: ua.ReferenceTypeIDHasSubtype, IsInverse: true, TargetID: ua.NewExpandedNodeID(ua.ObjectTypeIDBaseObjectType)}},
			false,
		),
		server.NewObjectTypeNode(
			srv,
			functionalGroupTypeID,
			ua.NewQualifiedName(diNS, "FunctionalGroupType"),
			ua.LocalizedText{Text: "FunctionalGroupType"},
			ua.LocalizedText{Text: "FunctionalGroupType"},
			nil,
			[]ua.Reference{{ReferenceTypeID: ua.ReferenceTypeIDHasSubtype, IsInverse: true, TargetID: ua.NewExpandedNodeID(ua.ObjectTypeIDBaseObjectType)}},
			false,
		),
		server.NewReferenceTypeNode(
			srv,
			hasInputVarID,
			ua.NewQualifiedName(ns, "HasInputVar"),
			ua.LocalizedText{Text: "HasInputVar"},
			ua.LocalizedText{Text: "Siemens input variable reference"},
			nil,
			[]ua.Reference{{ReferenceTypeID: ua.ReferenceTypeIDHasSubtype, IsInverse: true, TargetID: ua.NewExpandedNodeID(ua.ReferenceTypeIDHasComponent)}},
			false,
			false,
			ua.LocalizedText{Text: "InputVarOf"},
		),
		server.NewReferenceTypeNode(
			srv,
			hasOutputVarID,
			ua.NewQualifiedName(ns, "HasOutputVar"),
			ua.LocalizedText{Text: "HasOutputVar"},
			ua.LocalizedText{Text: "Siemens output variable reference"},
			nil,
			[]ua.Reference{{ReferenceTypeID: ua.ReferenceTypeIDHasSubtype, IsInverse: true, TargetID: ua.NewExpandedNodeID(ua.ReferenceTypeIDHasComponent)}},
			false,
			false,
			ua.LocalizedText{Text: "OutputVarOf"},
		),
		server.NewReferenceTypeNode(
			srv,
			hasLocalVarID,
			ua.NewQualifiedName(ns, "HasLocalVar"),
			ua.LocalizedText{Text: "HasLocalVar"},
			ua.LocalizedText{Text: "Siemens local/static variable reference"},
			nil,
			[]ua.Reference{{ReferenceTypeID: ua.ReferenceTypeIDHasSubtype, IsInverse: true, TargetID: ua.NewExpandedNodeID(ua.ReferenceTypeIDHasComponent)}},
			false,
			false,
			ua.LocalizedText{Text: "LocalVarOf"},
		),
		root,
	}
	for _, folderName := range opcuaRootFunctionalGroupNames() {
		folderID := ua.NewNodeIDString(ns, folderName)
		nodes = append(nodes, server.NewObjectNode(
			srv,
			folderID,
			ua.NewQualifiedName(ns, folderName),
			ua.LocalizedText{Text: folderName},
			ua.LocalizedText{Text: folderName},
			nil,
			[]ua.Reference{
				{ReferenceTypeID: ua.ReferenceTypeIDHasComponent, IsInverse: true, TargetID: ua.NewExpandedNodeID(rootID)},
				{ReferenceTypeID: ua.ReferenceTypeIDHasTypeDefinition, IsInverse: false, TargetID: ua.NewExpandedNodeID(functionalGroupTypeID)},
			},
			0,
		))
	}
	variableNodeIDs := map[string]struct{}{}
	for _, tag := range tags {
		if strings.TrimSpace(tag.NodeID) != "" && !tag.BrowseObject {
			variableNodeIDs[tag.NodeID] = struct{}{}
		}
	}
	knownObjects := map[string]struct{}{opcuaRootNodeID: {}}
	for _, folderName := range opcuaRootFunctionalGroupNames() {
		knownObjects[folderName] = struct{}{}
	}
	addObject := func(spec opcuaBrowseParent) {
		if strings.TrimSpace(spec.NodeID) == "" {
			return
		}
		if _, ok := variableNodeIDs[spec.NodeID]; ok {
			return
		}
		if _, ok := knownObjects[spec.NodeID]; ok {
			return
		}
		knownObjects[spec.NodeID] = struct{}{}
		parentID := rootID
		if strings.TrimSpace(spec.ParentNodeID) != "" {
			parentID = ua.NewNodeIDString(ns, spec.ParentNodeID)
		}
		refType := opcuaReferenceTypeForKind(ns, spec.ReferenceKind)
		display := spec.DisplayName
		if strings.TrimSpace(display) == "" {
			display = spec.BrowseName
		}
		typeDefinition := ua.ObjectTypeIDBaseObjectType
		if opcuaIsSectionFolderName(spec.BrowseName) {
			typeDefinition = ua.ObjectTypeIDFolderType
		}
		nodes = append(nodes, server.NewObjectNode(
			srv,
			ua.NewNodeIDString(ns, spec.NodeID),
			ua.NewQualifiedName(ns, spec.BrowseName),
			ua.LocalizedText{Text: display},
			ua.LocalizedText{Text: display},
			nil,
			[]ua.Reference{
				{ReferenceTypeID: refType, IsInverse: true, TargetID: ua.NewExpandedNodeID(parentID)},
				{ReferenceTypeID: ua.ReferenceTypeIDHasTypeDefinition, IsInverse: false, TargetID: ua.NewExpandedNodeID(typeDefinition)},
			},
			0,
		))
	}
	if runtimeHasDebugSnapshotOPC && debugSnapshots != nil {
		debugFolderID := ua.NewNodeIDString(ns, opcuaDebugFolderID)
		snapshotsFolderID := ua.NewNodeIDString(ns, opcuaSnapshotsFolderID)
		debugFolder := server.NewObjectNode(
			srv,
			debugFolderID,
			ua.NewQualifiedName(ns, "Debug"),
			ua.LocalizedText{Text: "Debug"},
			ua.LocalizedText{Text: "PLC Debug Data"},
			nil,
			[]ua.Reference{
				{ReferenceTypeID: ua.ReferenceTypeIDOrganizes, IsInverse: true, TargetID: ua.NewExpandedNodeID(rootID)},
				{ReferenceTypeID: ua.ReferenceTypeIDHasTypeDefinition, IsInverse: false, TargetID: ua.NewExpandedNodeID(ua.ObjectTypeIDFolderType)},
			},
			0,
		)
		snapshotsFolder := server.NewObjectNode(
			srv,
			snapshotsFolderID,
			ua.NewQualifiedName(ns, "Snapshots"),
			ua.LocalizedText{Text: "Snapshots"},
			ua.LocalizedText{Text: "Paused statement snapshots"},
			nil,
			[]ua.Reference{
				{ReferenceTypeID: ua.ReferenceTypeIDOrganizes, IsInverse: true, TargetID: ua.NewExpandedNodeID(debugFolderID)},
				{ReferenceTypeID: ua.ReferenceTypeIDHasTypeDefinition, IsInverse: false, TargetID: ua.NewExpandedNodeID(ua.ObjectTypeIDFolderType)},
			},
			0,
		)
		nodes = append(nodes, debugFolder, snapshotsFolder)
		knownObjects[opcuaDebugFolderID] = struct{}{}
		knownObjects[opcuaSnapshotsFolderID] = struct{}{}
		for _, entry := range debugSnapshots.Statements() {
			debugID := strings.TrimSpace(entry.DebugID)
			if debugID == "" {
				continue
			}
			lineFolderID := ua.NewNodeIDString(ns, opcuaSnapshotsFolderID+"."+debugID)
			lineFolder := server.NewObjectNode(
				srv,
				lineFolderID,
				ua.NewQualifiedName(ns, debugID),
				ua.LocalizedText{Text: debugID},
				ua.LocalizedText{Text: "Statement snapshot"},
				nil,
				[]ua.Reference{
					{ReferenceTypeID: ua.ReferenceTypeIDOrganizes, IsInverse: true, TargetID: ua.NewExpandedNodeID(snapshotsFolderID)},
					{ReferenceTypeID: ua.ReferenceTypeIDHasTypeDefinition, IsInverse: false, TargetID: ua.NewExpandedNodeID(ua.ObjectTypeIDFolderType)},
				},
				0,
			)
			nodes = append(nodes, lineFolder)
			knownObjects[opcuaSnapshotsFolderID+"."+debugID] = struct{}{}
			seen := map[string]struct{}{}
			for _, ref := range entry.Variables {
				name := strings.TrimSpace(ref.Name)
				if name == "" {
					continue
				}
				key := strings.ToUpper(name)
				if _, ok := seen[key]; ok {
					continue
				}
				seen[key] = struct{}{}
				varName := name
				varDebugID := debugID
				variableNodeID := ua.NewNodeIDString(ns, opcuaSnapshotsFolderID+"."+debugID+"."+name)
				variableNode := server.NewVariableNode(
					srv,
					variableNodeID,
					ua.NewQualifiedName(ns, name),
					ua.LocalizedText{Text: name},
					ua.LocalizedText{Text: name},
					nil,
					[]ua.Reference{{ReferenceTypeID: ua.ReferenceTypeIDOrganizes, IsInverse: true, TargetID: ua.NewExpandedNodeID(lineFolderID)}},
					ua.NewDataValue(debugSnapshots.ReadValue(varDebugID, varName), 0, time.Now(), 0, time.Now(), 0),
					ua.DataTypeIDBaseDataType,
					ua.ValueRankScalar,
					[]uint32{},
					ua.AccessLevelsCurrentRead,
					opcuaMinimumSamplingInterval,
					false,
					nil,
				)
				variableNode.SetReadValueHandler(func(_ *server.Session, _ ua.ReadValueID) ua.DataValue {
					return ua.NewDataValue(debugSnapshots.ReadValue(varDebugID, varName), 0, time.Now(), 0, time.Now(), 0)
				})
				nodes = append(nodes, variableNode)
			}
		}
	}
	for _, tag := range tags {
		for _, parent := range tag.Parents {
			addObject(parent)
		}
	}

	writablePermissions := opcuaWritableRolePermissions()
	addedVariableNodeIDs := map[string]struct{}{}
	addVariableNode := func(tag memoryTag, nodeID string, includeBrowseReferences bool) {
		if strings.TrimSpace(nodeID) == "" {
			return
		}
		if _, ok := knownObjects[nodeID]; ok {
			return
		}
		if _, ok := addedVariableNodeIDs[nodeID]; ok {
			return
		}
		addedVariableNodeIDs[nodeID] = struct{}{}
		tagNodeID := ua.NewNodeIDString(ns, nodeID)
		tagBrowseName := ua.NewQualifiedName(ns, tag.BrowseName)
		tagDisplayName := ua.LocalizedText{Text: tag.BrowseName}
		tagCopy := tag
		accessLevel := byte(ua.AccessLevelsCurrentRead)
		rolePermissions := []ua.RolePermissionType(nil)
		if tag.Writable {
			accessLevel |= ua.AccessLevelsCurrentWrite
			rolePermissions = writablePermissions
		}
		refs := []ua.Reference{
			{ReferenceTypeID: ua.ReferenceTypeIDHasTypeDefinition, IsInverse: false, TargetID: ua.NewExpandedNodeID(ua.VariableTypeIDBaseDataVariableType)},
		}
		if includeBrowseReferences {
			refs = append([]ua.Reference{
				{ReferenceTypeID: opcuaReferenceTypeForKind(ns, tag.ParentReferenceKind), IsInverse: true, TargetID: ua.NewExpandedNodeID(ua.NewNodeIDString(ns, tag.ParentNodeID))},
			}, refs...)
		}
		v := server.NewVariableNode(
			srv,
			tagNodeID,
			tagBrowseName,
			tagDisplayName,
			tagDisplayName,
			rolePermissions,
			refs,
			ua.NewDataValue(readOPCUATagValue(snapshot, tagCopy), 0, time.Now(), 0, time.Now(), 0),
			opcuaDataTypeForTag(tagCopy),
			ua.ValueRankScalar,
			[]uint32{},
			accessLevel,
			opcuaMinimumSamplingInterval,
			false,
			nil,
		)
		v.SetReadValueHandler(func(_ *server.Session, _ ua.ReadValueID) ua.DataValue {
			return ua.NewDataValue(readOPCUATagValue(snapshot, tagCopy), 0, time.Now(), 0, time.Now(), 0)
		})
		v.SetWriteValueHandler(func(_ *server.Session, req ua.WriteValue) (ua.DataValue, ua.StatusCode) {
			if !tagCopy.Writable {
				return req.Value, ua.BadNotWritable
			}
			written, status := writeOPCUATagValue(snapshot, tagCopy, req.Value.Value)
			if status.IsBad() {
				return req.Value, status
			}
			return ua.NewDataValue(written, 0, time.Now(), 0, time.Now(), 0), ua.Good
		})
		nodes = append(nodes, v)
	}
	for _, tag := range tags {
		if tag.BrowseObject {
			continue
		}
		seenNodeIDs := map[string]struct{}{}
		addVariableNode(tag, tag.NodeID, true)
		seenNodeIDs[tag.NodeID] = struct{}{}
		for _, alias := range tag.AliasNodeIDs {
			if strings.TrimSpace(alias) == "" {
				continue
			}
			if _, ok := seenNodeIDs[alias]; ok {
				continue
			}
			seenNodeIDs[alias] = struct{}{}
			addVariableNode(tag, alias, false)
		}
	}

	return nm.AddNodes(nodes...)
}

func opcuaReferenceTypeForKind(ns uint16, kind string) ua.NodeID {
	switch strings.ToLower(strings.TrimSpace(kind)) {
	case "input":
		return ua.NewNodeIDNumeric(ns, 4003)
	case "output":
		return ua.NewNodeIDNumeric(ns, 4004)
	case "local", "static":
		return ua.NewNodeIDNumeric(ns, 4005)
	case "component":
		return ua.ReferenceTypeIDHasComponent
	default:
		return ua.ReferenceTypeIDOrganizes
	}
}

func opcuaDataTypeForTag(tag memoryTag) ua.NodeID {
	if tag.Structured {
		return ua.DataTypeIDString
	}
	if opcuaTagIsTime(tag) {
		return ua.DataTypeIDInt32
	}
	switch opcuaScalarTypeName(tag.TypeRef) {
	case "BOOL":
		return ua.DataTypeIDBoolean
	case "SINT":
		return ua.DataTypeIDSByte
	case "BYTE", "USINT", "CHAR":
		return ua.DataTypeIDByte
	case "INT":
		return ua.DataTypeIDInt16
	case "WORD", "UINT", "WCHAR":
		return ua.DataTypeIDUInt16
	case "DINT":
		return ua.DataTypeIDInt32
	case "DWORD", "UDINT":
		return ua.DataTypeIDUInt32
	case "LINT":
		return ua.DataTypeIDInt64
	case "LWORD", "ULINT":
		return ua.DataTypeIDUInt64
	case "REAL":
		return ua.DataTypeIDFloat
	case "LREAL":
		return ua.DataTypeIDDouble
	case "STRING":
		return ua.DataTypeIDString
	}
	if typ, ok := memoryLeafType(tag.Index); ok && opcuaReflectTypeIsStringStorage(typ) {
		return ua.DataTypeIDString
	}
	if k, _ := memoryLeafKind(tag.Index); k != reflect.Invalid {
		switch k {
		case reflect.Bool:
			return ua.DataTypeIDBoolean
		case reflect.Int8:
			return ua.DataTypeIDSByte
		case reflect.Uint8:
			return ua.DataTypeIDByte
		case reflect.Int16:
			return ua.DataTypeIDInt16
		case reflect.Uint16:
			return ua.DataTypeIDUInt16
		case reflect.Int32:
			return ua.DataTypeIDInt32
		case reflect.Uint32:
			return ua.DataTypeIDUInt32
		case reflect.Int, reflect.Int64:
			return ua.DataTypeIDInt64
		case reflect.Uint, reflect.Uint64, reflect.Uintptr:
			return ua.DataTypeIDUInt64
		case reflect.Float32:
			return ua.DataTypeIDFloat
		case reflect.Float64:
			return ua.DataTypeIDDouble
		case reflect.String:
			return ua.DataTypeIDString
		}
	}
	return ua.DataTypeIDBaseDataType
}

func opcuaScalarTypeName(typeRef string) string {
	t := strings.TrimSpace(typeRef)
	for strings.HasPrefix(t, "_.") {
		t = strings.TrimSpace(strings.TrimPrefix(t, "_."))
	}
	if idx := strings.LastIndex(t, "."); idx >= 0 {
		t = strings.TrimSpace(t[idx+1:])
	}
	t = strings.ToUpper(strings.TrimSpace(strings.Trim(t, "\"")))
	if strings.HasPrefix(t, "STRING") || strings.HasPrefix(t, "WSTRING") {
		return "STRING"
	}
	return t
}

func opcuaTagIsTime(tag memoryTag) bool {
	if opcuaScalarTypeName(tag.TypeRef) == "TIME" {
		return true
	}
	typ, ok := memoryLeafType(tag.Index)
	if !ok || typ == nil {
		return false
	}
	for typ.Kind() == reflect.Ptr {
		typ = typ.Elem()
	}
	return strings.EqualFold(typ.Name(), "TIME")
}

func readOPCUATagValue(snapshot *sharedMemory, tag memoryTag) any {
	if snapshot == nil || len(tag.Index) == 0 {
		return ""
	}
	v := reflect.ValueOf(snapshot.Snapshot()).FieldByIndex(tag.Index)
	if tag.Structured {
		return readOPCUAStructJSON(v)
	}
	if opcuaScalarTypeName(tag.TypeRef) == "STRING" || opcuaReflectValueIsStringStorage(v) {
		if s, ok := reflectStringLikeValue(v); ok {
			return s
		}
	}
	if opcuaTagIsTime(tag) {
		ns, ok := reflectValueAsInt64(v)
		if !ok {
			return int32(0)
		}
		ms := ns / int64(time.Millisecond)
		const maxInt32 = int64(1<<31 - 1)
		const minInt32 = int64(-1 << 31)
		if ms > maxInt32 {
			return int32(maxInt32)
		}
		if ms < minInt32 {
			return int32(minInt32)
		}
		return int32(ms)
	}
	return readReflectValue(v)
}

func readOPCUATagValueAt(snapshot *sharedMemory, index []int) any {
	if snapshot == nil || len(index) == 0 {
		return ""
	}
	v := reflect.ValueOf(snapshot.Snapshot()).FieldByIndex(index)
	return readReflectValue(v)
}

func writeOPCUATagValue(snapshot *sharedMemory, tag memoryTag, value any) (any, ua.StatusCode) {
	if snapshot == nil {
		return nil, ua.BadNotWritable
	}
	runtimeValue := value
	if tag.Structured {
		written, status := snapshot.Write(tag.Index, runtimeValue)
		if status.IsBad() {
			return nil, status
		}
		_ = written
		return readOPCUATagValue(snapshot, tag), ua.Good
	}
	if opcuaTagIsTime(tag) {
		ms, status := coerceReflectInt64(value)
		if status.IsBad() {
			return nil, status
		}
		runtimeValue = ms * int64(time.Millisecond)
	}
	written, status := snapshot.Write(tag.Index, runtimeValue)
	if status.IsBad() {
		return nil, status
	}
	if opcuaTagIsTime(tag) {
		return readOPCUATagValue(snapshot, tag), ua.Good
	}
	return written, ua.Good
}

func reflectValueAsInt64(v reflect.Value) (int64, bool) {
	if !v.IsValid() {
		return 0, false
	}
	for v.Kind() == reflect.Pointer {
		if v.IsNil() {
			return 0, false
		}
		v = v.Elem()
	}
	switch v.Kind() {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return v.Int(), true
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		u := v.Uint()
		if u > math.MaxInt64 {
			return 0, false
		}
		return int64(u), true
	default:
		return 0, false
	}
}

func readReflectValue(v reflect.Value) any {
	if !v.IsValid() {
		return ""
	}
	for v.Kind() == reflect.Pointer {
		if v.IsNil() {
			return ""
		}
		v = v.Elem()
	}
	switch v.Kind() {
	case reflect.Bool:
		return v.Bool()
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return v.Int()
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return v.Uint()
	case reflect.Float32, reflect.Float64:
		return v.Float()
	case reflect.String:
		return v.String()
	default:
		return formatValue(v)
	}
}

func readOPCUAStructJSON(v reflect.Value) string {
	data, err := json.Marshal(opcuaJSONValue(v, ""))
	if err != nil {
		return "{}"
	}
	return string(data)
}

func opcuaJSONValue(v reflect.Value, typeRef string) any {
	if !v.IsValid() {
		return nil
	}
	for v.Kind() == reflect.Pointer {
		if v.IsNil() {
			return nil
		}
		v = v.Elem()
	}
	if opcuaReflectValueIsTime(v, typeRef) {
		ns, ok := reflectValueAsInt64(v)
		if !ok {
			return int64(0)
		}
		return ns / int64(time.Millisecond)
	}
	if opcuaScalarTypeName(typeRef) == "STRING" || opcuaReflectValueIsStringStorage(v) {
		if s, ok := reflectStringLikeValue(v); ok {
			return s
		}
		return formatValue(v)
	}
	switch v.Kind() {
	case reflect.Bool:
		return v.Bool()
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return v.Int()
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return v.Uint()
	case reflect.Float32, reflect.Float64:
		f := v.Float()
		if math.IsNaN(f) || math.IsInf(f, 0) {
			return nil
		}
		return f
	case reflect.String:
		return v.String()
	case reflect.Array, reflect.Slice:
		out := make([]any, 0, v.Len())
		elemTypeRef := opcuaArrayElementTypeRef(typeRef)
		for i := 0; i < v.Len(); i++ {
			out = append(out, opcuaJSONValue(v.Index(i), elemTypeRef))
		}
		return out
	case reflect.Struct:
		out := map[string]any{}
		typ := v.Type()
		for i := 0; i < v.NumField(); i++ {
			field := typ.Field(i)
			if strings.HasPrefix(field.Name, "SCLH_") || strings.HasPrefix(field.Name, "__scl") {
				continue
			}
			meta := opcuaFieldMetadataFromStructField(field)
			if meta.Name == "" {
				continue
			}
			out[meta.Name] = opcuaJSONValue(v.Field(i), meta.TypeRef)
		}
		return out
	default:
		return formatValue(v)
	}
}

func opcuaArrayElementTypeRef(typeRef string) string {
	t := strings.TrimSpace(typeRef)
	for strings.HasSuffix(t, ";") {
		t = strings.TrimSpace(strings.TrimSuffix(t, ";"))
	}
	up := strings.ToUpper(t)
	if !strings.HasPrefix(up, "ARRAY[") {
		return ""
	}
	idx := strings.LastIndex(up, " OF ")
	if idx < 0 || idx+4 >= len(t) {
		return ""
	}
	return strings.TrimSpace(t[idx+4:])
}

func opcuaReflectValueIsTime(v reflect.Value, typeRef string) bool {
	if opcuaScalarTypeName(typeRef) == "TIME" {
		return true
	}
	if !v.IsValid() {
		return false
	}
	typ := v.Type()
	for typ.Kind() == reflect.Pointer {
		typ = typ.Elem()
	}
	return strings.EqualFold(typ.Name(), "TIME")
}

func reflectStringLikeValue(v reflect.Value) (string, bool) {
	if !v.IsValid() {
		return "", false
	}
	for v.Kind() == reflect.Pointer {
		if v.IsNil() {
			return "", true
		}
		v = v.Elem()
	}
	if v.Kind() == reflect.String {
		return v.String(), true
	}
	if s, ok := reflectSiemensStringStorageValue(v); ok {
		return s, true
	}
	if v.CanInterface() {
		if method := v.MethodByName("String"); method.IsValid() && method.Type().NumIn() == 0 && method.Type().NumOut() == 1 && method.Type().Out(0).Kind() == reflect.String {
			out := method.Call(nil)
			return out[0].String(), true
		}
		if stringer, ok := v.Interface().(fmt.Stringer); ok {
			return stringer.String(), true
		}
	}
	if v.CanAddr() {
		addressable := reflect.NewAt(v.Type(), unsafe.Pointer(v.UnsafeAddr())).Elem()
		if method := addressable.MethodByName("String"); method.IsValid() && method.Type().NumIn() == 0 && method.Type().NumOut() == 1 && method.Type().Out(0).Kind() == reflect.String {
			out := method.Call(nil)
			return out[0].String(), true
		}
		if addressable.CanInterface() {
			if stringer, ok := addressable.Interface().(fmt.Stringer); ok {
				return stringer.String(), true
			}
		}
	}
	return "", false
}

func opcuaReflectValueIsStringStorage(v reflect.Value) bool {
	if !v.IsValid() {
		return false
	}
	return opcuaReflectTypeIsStringStorage(v.Type())
}

func opcuaReflectTypeIsStringStorage(typ reflect.Type) bool {
	if typ == nil {
		return false
	}
	for typ.Kind() == reflect.Pointer {
		typ = typ.Elem()
	}
	if typ.Kind() != reflect.Struct {
		return false
	}
	lenField, ok := typ.FieldByName("Len")
	if !ok {
		return false
	}
	switch lenField.Type.Kind() {
	case reflect.Uint8, reflect.Uint16:
	default:
		return false
	}
	dataField, ok := typ.FieldByName("Data")
	if !ok {
		return false
	}
	dataType := dataField.Type
	if dataType.Kind() != reflect.Array && dataType.Kind() != reflect.Slice {
		return false
	}
	switch dataType.Elem().Kind() {
	case reflect.Uint8, reflect.Uint16:
		return true
	default:
		return false
	}
}

func reflectSiemensStringStorageValue(v reflect.Value) (string, bool) {
	if !v.IsValid() || v.Kind() != reflect.Struct {
		return "", false
	}
	lenField := v.FieldByName("Len")
	dataField := v.FieldByName("Data")
	if !lenField.IsValid() || !dataField.IsValid() {
		return "", false
	}
	n64, ok := reflectValueAsInt64(lenField)
	if !ok || n64 < 0 {
		return "", false
	}
	n := int(n64)
	if dataField.Kind() != reflect.Array && dataField.Kind() != reflect.Slice {
		return "", false
	}
	if n > dataField.Len() {
		n = dataField.Len()
	}
	elemKind := dataField.Type().Elem().Kind()
	switch elemKind {
	case reflect.Uint8:
		buf := make([]byte, 0, n)
		for i := 0; i < n; i++ {
			buf = append(buf, byte(dataField.Index(i).Uint()))
		}
		return string(buf), true
	case reflect.Uint16:
		runes := make([]rune, 0, n)
		for i := 0; i < n; i++ {
			runes = append(runes, rune(dataField.Index(i).Uint()))
		}
		return string(runes), true
	default:
		return "", false
	}
}

func setReflectStringLikeValue(target reflect.Value, value any) (ua.StatusCode, bool) {
	if !target.IsValid() || !target.CanAddr() {
		return ua.Good, false
	}
	method := target.Addr().MethodByName("SetString")
	if !method.IsValid() {
		return ua.Good, false
	}
	v, ok := value.(string)
	if !ok {
		return ua.BadTypeMismatch, true
	}
	method.Call([]reflect.Value{reflect.ValueOf(v)})
	return ua.Good, true
}

func setReflectStructFromJSON(target reflect.Value, value any) ua.StatusCode {
	var decoded any
	switch v := value.(type) {
	case string:
		if strings.TrimSpace(v) == "" {
			return ua.BadTypeMismatch
		}
		if err := json.Unmarshal([]byte(v), &decoded); err != nil {
			return ua.BadTypeMismatch
		}
	case []byte:
		if len(v) == 0 {
			return ua.BadTypeMismatch
		}
		if err := json.Unmarshal(v, &decoded); err != nil {
			return ua.BadTypeMismatch
		}
	default:
		data, err := json.Marshal(value)
		if err != nil {
			return ua.BadTypeMismatch
		}
		if err := json.Unmarshal(data, &decoded); err != nil {
			return ua.BadTypeMismatch
		}
	}
	return setReflectValueFromJSON(target, decoded, "")
}

func setReflectValueFromJSON(target reflect.Value, value any, typeRef string) ua.StatusCode {
	if !target.IsValid() {
		return ua.BadNodeIDUnknown
	}
	for target.Kind() == reflect.Pointer {
		if target.IsNil() {
			target.Set(reflect.New(target.Type().Elem()))
		}
		target = target.Elem()
	}
	if !target.CanSet() && target.CanAddr() {
		target = reflect.NewAt(target.Type(), unsafe.Pointer(target.UnsafeAddr())).Elem()
	}
	if !target.CanSet() {
		return ua.BadNotWritable
	}
	if status, ok := setReflectStringLikeValue(target, value); ok {
		return status
	}
	if opcuaReflectValueIsTime(target, typeRef) {
		ms, status := coerceReflectInt64(value)
		if status.IsBad() {
			return status
		}
		ns := ms * int64(time.Millisecond)
		if target.OverflowInt(ns) {
			return ua.BadOutOfRange
		}
		target.SetInt(ns)
		return ua.Good
	}
	switch target.Kind() {
	case reflect.Struct:
		obj, ok := value.(map[string]any)
		if !ok {
			return ua.BadTypeMismatch
		}
		for name, childValue := range obj {
			field, childTypeRef, ok := opcuaStructFieldByJSONName(target, name)
			if !ok {
				return ua.BadTypeMismatch
			}
			if status := setReflectValueFromJSON(field, childValue, childTypeRef); status.IsBad() {
				return status
			}
		}
		return ua.Good
	case reflect.Array:
		items, ok := value.([]any)
		if !ok {
			return ua.BadTypeMismatch
		}
		if len(items) > target.Len() {
			return ua.BadOutOfRange
		}
		elemTypeRef := opcuaArrayElementTypeRef(typeRef)
		for i, item := range items {
			if status := setReflectValueFromJSON(target.Index(i), item, elemTypeRef); status.IsBad() {
				return status
			}
		}
		return ua.Good
	case reflect.Slice:
		items, ok := value.([]any)
		if !ok {
			return ua.BadTypeMismatch
		}
		if target.IsNil() || target.Len() != len(items) {
			target.Set(reflect.MakeSlice(target.Type(), len(items), len(items)))
		}
		elemTypeRef := opcuaArrayElementTypeRef(typeRef)
		for i, item := range items {
			if status := setReflectValueFromJSON(target.Index(i), item, elemTypeRef); status.IsBad() {
				return status
			}
		}
		return ua.Good
	default:
		return setReflectValue(target, value)
	}
}

func opcuaStructFieldByJSONName(target reflect.Value, name string) (reflect.Value, string, bool) {
	typ := target.Type()
	for i := 0; i < target.NumField(); i++ {
		field := typ.Field(i)
		if strings.HasPrefix(field.Name, "SCLH_") || strings.HasPrefix(field.Name, "__scl") {
			continue
		}
		meta := opcuaFieldMetadataFromStructField(field)
		if meta.Name == "" {
			continue
		}
		if strings.EqualFold(meta.Name, name) || strings.EqualFold(field.Name, name) {
			return target.Field(i), meta.TypeRef, true
		}
	}
	return reflect.Value{}, "", false
}

func setReflectValue(target reflect.Value, value any) ua.StatusCode {
	if !target.IsValid() {
		return ua.BadNodeIDUnknown
	}
	for target.Kind() == reflect.Pointer {
		if target.IsNil() {
			target.Set(reflect.New(target.Type().Elem()))
		}
		target = target.Elem()
	}
	if !target.CanSet() && target.CanAddr() {
		target = reflect.NewAt(target.Type(), unsafe.Pointer(target.UnsafeAddr())).Elem()
	}
	if !target.CanSet() {
		return ua.BadNotWritable
	}
	if value == nil {
		return ua.BadTypeMismatch
	}
	if status, ok := setReflectStringLikeValue(target, value); ok {
		return status
	}
	source := reflect.ValueOf(value)
	switch target.Kind() {
	case reflect.Bool:
		v, ok := value.(bool)
		if !ok {
			return ua.BadTypeMismatch
		}
		target.SetBool(v)
		return ua.Good
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v, status := coerceReflectInt64(value)
		if status.IsBad() {
			return status
		}
		if target.OverflowInt(v) {
			return ua.BadOutOfRange
		}
		target.SetInt(v)
		return ua.Good
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		v, status := coerceReflectUint64(value)
		if status.IsBad() {
			return status
		}
		if target.OverflowUint(v) {
			return ua.BadOutOfRange
		}
		target.SetUint(v)
		return ua.Good
	case reflect.Float32, reflect.Float64:
		v, status := coerceReflectFloat64(value)
		if status.IsBad() {
			return status
		}
		if target.OverflowFloat(v) {
			return ua.BadOutOfRange
		}
		target.SetFloat(v)
		return ua.Good
	case reflect.String:
		v, ok := value.(string)
		if !ok {
			return ua.BadTypeMismatch
		}
		target.SetString(v)
		return ua.Good
	case reflect.Struct:
		if source.IsValid() && source.Type().AssignableTo(target.Type()) {
			target.Set(source)
			return ua.Good
		}
		if source.IsValid() && source.Type().ConvertibleTo(target.Type()) {
			target.Set(source.Convert(target.Type()))
			return ua.Good
		}
		return setReflectStructFromJSON(target, value)
	default:
		if source.IsValid() && source.Type().AssignableTo(target.Type()) {
			target.Set(source)
			return ua.Good
		}
		if source.IsValid() && source.Type().ConvertibleTo(target.Type()) {
			target.Set(source.Convert(target.Type()))
			return ua.Good
		}
		return ua.BadTypeMismatch
	}
}

func coerceReflectInt64(value any) (int64, ua.StatusCode) {
	rv := reflect.ValueOf(value)
	if !rv.IsValid() {
		return 0, ua.BadTypeMismatch
	}
	switch rv.Kind() {
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return rv.Int(), ua.Good
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		v := rv.Uint()
		if v > math.MaxInt64 {
			return 0, ua.BadOutOfRange
		}
		return int64(v), ua.Good
	case reflect.Float32, reflect.Float64:
		v := rv.Float()
		if math.IsNaN(v) || math.IsInf(v, 0) {
			return 0, ua.BadTypeMismatch
		}
		if math.Trunc(v) != v {
			return 0, ua.BadTypeMismatch
		}
		if v < math.MinInt64 || v > math.MaxInt64 {
			return 0, ua.BadOutOfRange
		}
		return int64(v), ua.Good
	default:
		return 0, ua.BadTypeMismatch
	}
}

func coerceReflectUint64(value any) (uint64, ua.StatusCode) {
	rv := reflect.ValueOf(value)
	if !rv.IsValid() {
		return 0, ua.BadTypeMismatch
	}
	switch rv.Kind() {
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return rv.Uint(), ua.Good
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		v := rv.Int()
		if v < 0 {
			return 0, ua.BadOutOfRange
		}
		return uint64(v), ua.Good
	case reflect.Float32, reflect.Float64:
		v := rv.Float()
		if math.IsNaN(v) || math.IsInf(v, 0) {
			return 0, ua.BadTypeMismatch
		}
		if math.Trunc(v) != v {
			return 0, ua.BadTypeMismatch
		}
		if v < 0 || v > math.MaxUint64 {
			return 0, ua.BadOutOfRange
		}
		return uint64(v), ua.Good
	default:
		return 0, ua.BadTypeMismatch
	}
}

func coerceReflectFloat64(value any) (float64, ua.StatusCode) {
	rv := reflect.ValueOf(value)
	if !rv.IsValid() {
		return 0, ua.BadTypeMismatch
	}
	switch rv.Kind() {
	case reflect.Float32, reflect.Float64:
		v := rv.Float()
		if math.IsNaN(v) || math.IsInf(v, 0) {
			return 0, ua.BadTypeMismatch
		}
		return v, ua.Good
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return float64(rv.Int()), ua.Good
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return float64(rv.Uint()), ua.Good
	default:
		return 0, ua.BadTypeMismatch
	}
}

type tickMsg time.Time

func tickCmd() tea.Cmd {
	return tea.Tick(100*time.Millisecond, func(t time.Time) tea.Msg { return tickMsg(t) })
}

type model struct {
	snapshot *sharedMemory
	tags     []memoryTag
	values   []string
	filtered []int

	query      string
	searchMode bool
	cursor     int
	offset     int
	width      int
	height     int

	lastCycleNS     int64
	longestCycleNS  int64
	shortestCycleNS int64
	avgCycleNS      int64
}

func newModel(snapshot *sharedMemory, tags []memoryTag) model {
	m := model{
		snapshot: snapshot,
		tags:     tags,
		values:   make([]string, len(tags)),
		width:    100,
		height:   28,
	}
	m.applyFilter()
	m.refresh()
	return m
}

func (m model) Init() tea.Cmd {
	return tickCmd()
}

func (m model) Update(msg tea.Msg) (tea.Model, tea.Cmd) {
	switch msg := msg.(type) {
	case tickMsg:
		m.refresh()
		return m, tickCmd()
	case tea.WindowSizeMsg:
		m.width = msg.Width
		m.height = msg.Height
		return m, nil
	case tea.KeyMsg:
		switch msg.String() {
		case "ctrl+c", "q":
			return m, tea.Quit
		case "/":
			m.searchMode = true
			return m, nil
		case "esc":
			m.searchMode = false
			return m, nil
		case "enter":
			if m.searchMode {
				m.searchMode = false
				return m, nil
			}
		case "backspace", "ctrl+h":
			if m.searchMode && len(m.query) > 0 {
				m.query = m.query[:len(m.query)-1]
				m.applyFilter()
			}
			return m, nil
		case "up", "k":
			m.moveCursor(-1)
			return m, nil
		case "down", "j":
			m.moveCursor(1)
			return m, nil
		case "pgup":
			m.moveCursor(-m.visibleRows())
			return m, nil
		case "pgdown":
			m.moveCursor(m.visibleRows())
			return m, nil
		case "home":
			m.cursor = 0
			m.clampWindow()
			return m, nil
		case "end":
			if n := len(m.filtered); n > 0 {
				m.cursor = n - 1
			}
			m.clampWindow()
			return m, nil
		}

		if m.searchMode && len(msg.Runes) > 0 {
			m.query += string(msg.Runes)
			m.applyFilter()
		}
		return m, nil
	}
	return m, nil
}

func (m *model) refresh() {
	var mem plcruntime.Memory
	if m.snapshot != nil {
		mem = m.snapshot.SnapshotAndResetCycleWindow()
	}
	m.lastCycleNS, m.longestCycleNS, m.shortestCycleNS, m.avgCycleNS = readCycleStats(mem)
	if m.snapshot == nil {
		return
	}
	m.refreshValues(mem)
}

func (m *model) refreshValues(mem plcruntime.Memory) {
	rv := reflect.ValueOf(mem)
	for i, tag := range m.tags {
		if len(tag.Index) == 0 {
			m.values[i] = ""
			continue
		}
		m.values[i] = formatValue(rv.FieldByIndex(tag.Index))
	}
}

func (m *model) applyFilter() {
	needle := strings.ToLower(strings.TrimSpace(m.query))
	m.filtered = m.filtered[:0]
	for i, tag := range m.tags {
		if needle == "" || strings.Contains(strings.ToLower(tag.Name), needle) {
			m.filtered = append(m.filtered, i)
		}
	}
	if m.cursor >= len(m.filtered) {
		m.cursor = maxInt(len(m.filtered)-1, 0)
	}
	m.clampWindow()
}

func (m *model) moveCursor(delta int) {
	if len(m.filtered) == 0 {
		m.cursor = 0
		m.offset = 0
		return
	}
	m.cursor += delta
	if m.cursor < 0 {
		m.cursor = 0
	}
	if m.cursor >= len(m.filtered) {
		m.cursor = len(m.filtered) - 1
	}
	m.clampWindow()
}

func (m *model) clampWindow() {
	rows := m.visibleRows()
	if rows <= 0 {
		rows = 1
	}
	if m.offset > m.cursor {
		m.offset = m.cursor
	}
	if m.cursor >= m.offset+rows {
		m.offset = m.cursor - rows + 1
	}
	maxOffset := maxInt(len(m.filtered)-rows, 0)
	if m.offset > maxOffset {
		m.offset = maxOffset
	}
	if m.offset < 0 {
		m.offset = 0
	}
}

func (m model) visibleRows() int {
	rows := m.height - 10
	if rows < 6 {
		rows = 6
	}
	return rows
}

func (m model) View() string {
	headerTitle := lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("229")).Render("PLC Runtime")
	headerBody := fmt.Sprintf("Cycle(ms) avg=%s last=%s longest=%s shortest=%s", formatCycleMS(m.avgCycleNS), formatCycleMS(m.lastCycleNS), formatCycleMS(m.longestCycleNS), formatCycleMS(m.shortestCycleNS))
	header := lipgloss.NewStyle().Border(lipgloss.RoundedBorder()).Padding(0, 1).Render(headerTitle + "\n" + headerBody)

	searchPrefix := "search"
	if m.searchMode {
		searchPrefix = "search*"
	}
	searchLine := fmt.Sprintf("%s: %s", searchPrefix, m.query)
	metaLine := fmt.Sprintf("tags: %d/%d", len(m.filtered), len(m.tags))

	rows := make([]string, 0, m.visibleRows())
	start := m.offset
	end := minInt(len(m.filtered), start+m.visibleRows())
	for i := start; i < end; i++ {
		idx := m.filtered[i]
		cursor := "  "
		if i == m.cursor {
			cursor = "> "
		}
		row := fmt.Sprintf("%s%s = %s", cursor, m.tags[idx].Name, m.values[idx])
		if i == m.cursor {
			row = lipgloss.NewStyle().Bold(true).Foreground(lipgloss.Color("81")).Render(row)
		}
		rows = append(rows, row)
	}
	if len(rows) == 0 {
		rows = append(rows, "(no tags match current search)")
	}
	list := lipgloss.NewStyle().Border(lipgloss.RoundedBorder()).Padding(0, 1).Render(
		"Memory Tags\n" + searchLine + "\n" + metaLine + "\n\n" + strings.Join(rows, "\n"),
	)

	help := lipgloss.NewStyle().Faint(true).Render("/ search  arrows move  q quit")
	return lipgloss.JoinVertical(lipgloss.Left, header, list, help)
}

func buildMemoryTagIndex(t reflect.Type) []memoryTag {
	for t.Kind() == reflect.Ptr {
		t = t.Elem()
	}
	if t.Kind() != reflect.Struct {
		return nil
	}

	tags := make([]memoryTag, 0, t.NumField())
	var walk func(ctx opcuaWalkContext, st reflect.Type, path []int)
	walk = func(ctx opcuaWalkContext, st reflect.Type, path []int) {
		for i := 0; i < st.NumField(); i++ {
			field := st.Field(i)
			if strings.HasPrefix(field.Name, "SCLH_") || strings.HasPrefix(field.Name, "__scl") {
				continue
			}
			meta := opcuaFieldMetadataFromStructField(field)
			if meta.Name == "" {
				continue
			}
			nextPath := append(append([]int(nil), path...), i)
			ft := field.Type
			for ft.Kind() == reflect.Ptr {
				ft = ft.Elem()
			}
			nodePath := append(append([]string(nil), ctx.NodePath...), meta.Name)
			generatedPath := field.Name
			if ctx.GeneratedPath != "" {
				generatedPath = ctx.GeneratedPath + "." + field.Name
			}
			parentID := ctx.ParentNodeID
			parentRef := ctx.ParentReferenceKind
			parents := append([]opcuaBrowseParent(nil), ctx.Parents...)
			if parentID == "" {
				parentID = opcuaRootNodeID
				parentRef = "organizes"
			}
			if len(ctx.NodePath) == 0 {
				if folderName, folderRef := opcuaRootFunctionalGroupForMetadata(meta); folderName != "" {
					parentID = folderName
					parentRef = folderRef
				}
			}
			if ctx.HasSectionFolders {
				folderName, folderRef := opcuaSectionFolder(meta.Section)
				folderID := siemensFolderNodeID(ctx.NodePath, folderName)
				parents = append(parents, opcuaBrowseParent{
					NodeID:        folderID,
					BrowseName:    folderName,
					DisplayName:   folderName,
					ParentNodeID:  ctx.ParentNodeID,
					ReferenceKind: folderRef,
				})
				parentID = folderID
				parentRef = folderRef
			}
			if ft.Kind() == reflect.Struct && ft.NumField() > 0 && !opcuaReflectTypeIsStringStorage(ft) {
				nodeID := siemensNodeIDForPath(nodePath)
				browseObject := meta.FB || strings.EqualFold(meta.Kind, "db")
				tag := memoryTag{
					Name:                strings.Join(nodePath, "."),
					GeneratedName:       generatedPath,
					NodeID:              nodeID,
					BrowseName:          meta.Name,
					AliasNodeIDs:        siemensNodeIDAliasesForPath(nodePath),
					Index:               nextPath,
					TypeRef:             meta.TypeRef,
					Section:             meta.Section,
					Structured:          true,
					BrowseObject:        browseObject,
					Writable:            true,
					Parents:             parents,
					ParentNodeID:        parentID,
					ParentReferenceKind: parentRef,
				}
				tags = append(tags, tag)
				parents = append(parents, opcuaBrowseParent{
					NodeID:        nodeID,
					BrowseName:    meta.Name,
					DisplayName:   meta.Name,
					ParentNodeID:  parentID,
					ReferenceKind: parentRef,
				})
				childParentRef := "component"
				if meta.FB || strings.EqualFold(meta.Kind, "db") {
					childParentRef = "local"
				}
				childCtx := opcuaWalkContext{
					NodePath:            nodePath,
					GeneratedPath:       generatedPath,
					Parents:             parents,
					ParentNodeID:        nodeID,
					ParentReferenceKind: childParentRef,
					HasSectionFolders:   meta.FB || strings.EqualFold(meta.Kind, "db"),
				}
				walk(childCtx, ft, nextPath)
				continue
			}
			tag := memoryTag{
				Name:                strings.Join(nodePath, "."),
				GeneratedName:       generatedPath,
				NodeID:              siemensNodeIDForPath(nodePath),
				BrowseName:          meta.Name,
				AliasNodeIDs:        siemensNodeIDAliasesForPath(nodePath),
				Index:               nextPath,
				TypeRef:             meta.TypeRef,
				Section:             meta.Section,
				Writable:            true,
				Parents:             parents,
				ParentNodeID:        parentID,
				ParentReferenceKind: parentRef,
			}
			tags = append(tags, tag)
		}
	}
	rootCtx := opcuaWalkContext{ParentNodeID: opcuaRootNodeID, ParentReferenceKind: "organizes"}
	walk(rootCtx, t, nil)

	sort.Slice(tags, func(i, j int) bool {
		return strings.ToUpper(tags[i].Name) < strings.ToUpper(tags[j].Name)
	})
	return tags
}

type opcuaWalkContext struct {
	NodePath            []string
	GeneratedPath       string
	Parents             []opcuaBrowseParent
	ParentNodeID        string
	ParentReferenceKind string
	HasSectionFolders   bool
}

type opcuaFieldMetadata struct {
	Name    string
	TypeRef string
	Section string
	Kind    string
	FB      bool
}

func opcuaFieldMetadataFromStructField(field reflect.StructField) opcuaFieldMetadata {
	meta := opcuaFieldMetadata{
		Name:    field.Name,
		TypeRef: field.Type.Name(),
		Section: "static",
	}
	if raw := strings.TrimSpace(field.Tag.Get("opcua")); raw != "" {
		if values, err := url.ParseQuery(raw); err == nil {
			if v := strings.TrimSpace(values.Get("name")); v != "" {
				meta.Name = v
			}
			if v := strings.TrimSpace(values.Get("type")); v != "" {
				meta.TypeRef = v
			}
			if v := strings.TrimSpace(values.Get("section")); v != "" {
				meta.Section = v
			}
			meta.Kind = strings.TrimSpace(values.Get("kind"))
			meta.FB = strings.EqualFold(strings.TrimSpace(values.Get("fb")), "true")
		}
	}
	if meta.Name == "" || strings.HasPrefix(meta.Name, "SCLH_") || strings.HasPrefix(meta.Name, "__scl") {
		return opcuaFieldMetadata{}
	}
	if meta.TypeRef == "" {
		meta.TypeRef = field.Type.String()
	}
	meta.Section = opcuaCanonicalSection(meta.Section)
	return meta
}

func opcuaCanonicalSection(section string) string {
	switch strings.ToLower(strings.TrimSpace(section)) {
	case "input", "var_input", "var_in_out", "inout":
		return "input"
	case "output", "var_output":
		return "output"
	default:
		return "static"
	}
}

func opcuaRootFunctionalGroupForMetadata(meta opcuaFieldMetadata) (folderName string, referenceKind string) {
	switch strings.ToLower(strings.TrimSpace(meta.Kind)) {
	case "db":
		if meta.FB {
			return "DataBlocksInstance", "component"
		}
		return "DataBlocksGlobal", "component"
	}
	switch opcuaCanonicalSection(meta.Section) {
	case "input":
		return "Inputs", "component"
	case "output":
		return "Outputs", "component"
	default:
		return "Memory", "component"
	}
}

func opcuaSectionFolder(section string) (folderName string, referenceKind string) {
	switch opcuaCanonicalSection(section) {
	case "input":
		return "Inputs", "input"
	case "output":
		return "Outputs", "output"
	default:
		return "Static", "local"
	}
}

func opcuaIsSectionFolderName(name string) bool {
	switch strings.ToLower(strings.TrimSpace(name)) {
	case "inputs", "outputs", "static":
		return true
	default:
		return false
	}
}

func siemensNodeIDForPath(path []string) string {
	parts := make([]string, 0, len(path))
	for _, part := range path {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		parts = append(parts, quoteSiemensNodeIDPart(part))
	}
	return strings.Join(parts, ".")
}

func siemensNodeIDAliasesForPath(path []string) []string {
	if len(path) == 0 {
		return nil
	}
	last := strings.TrimSpace(strings.Trim(path[len(path)-1], "\""))
	if !siemensNodeIDPartCanBeUnquoted(last) {
		return nil
	}
	parts := make([]string, 0, len(path))
	for i, part := range path {
		part = strings.TrimSpace(part)
		if part == "" {
			continue
		}
		if i == len(path)-1 {
			parts = append(parts, last)
			continue
		}
		parts = append(parts, quoteSiemensNodeIDPart(part))
	}
	alias := strings.Join(parts, ".")
	if alias == "" || alias == siemensNodeIDForPath(path) {
		return nil
	}
	return []string{alias}
}

func siemensNodeIDPartCanBeUnquoted(part string) bool {
	if part == "" {
		return false
	}
	for i := 0; i < len(part); i++ {
		c := part[i]
		if i == 0 {
			if c != '_' && !((c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z')) {
				return false
			}
			continue
		}
		if c == '_' || (c >= '0' && c <= '9') || (c >= 'A' && c <= 'Z') || (c >= 'a' && c <= 'z') {
			continue
		}
		return false
	}
	return true
}

func siemensFolderNodeID(parentPath []string, folder string) string {
	parent := siemensNodeIDForPath(parentPath)
	if parent == "" {
		return strings.TrimSpace(folder)
	}
	return parent + "." + strings.TrimSpace(folder)
}

func quoteSiemensNodeIDPart(part string) string {
	part = strings.Trim(part, "\"")
	part = strings.ReplaceAll(part, "\\", "\\\\")
	part = strings.ReplaceAll(part, "\"", "\\\"")
	return "\"" + part + "\""
}

func formatValue(v reflect.Value) string {
	if !v.IsValid() {
		return "<invalid>"
	}
	if v.Kind() == reflect.Pointer {
		if v.IsNil() {
			return "<nil>"
		}
		return formatValue(v.Elem())
	}
	if v.CanInterface() {
		return fmt.Sprintf("%v", v.Interface())
	}
	switch v.Kind() {
	case reflect.Bool:
		return fmt.Sprintf("%t", v.Bool())
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64:
		return fmt.Sprintf("%d", v.Int())
	case reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Uintptr:
		return fmt.Sprintf("%d", v.Uint())
	case reflect.Float32, reflect.Float64:
		return fmt.Sprintf("%g", v.Float())
	case reflect.String:
		return v.String()
	default:
		return "<unexported>"
	}
}

func minInt(a, b int) int {
	if a < b {
		return a
	}
	return b
}

func maxInt(a, b int) int {
	if a > b {
		return a
	}
	return b
}

func formatCycleMS(ns int64) string {
	if ns < 0 {
		return "n/a"
	}
	ms := float64(ns) / 1_000_000.0
	if ms < 0.001 {
		return fmt.Sprintf("%.6fms", ms)
	}
	if ms < 1 {
		return fmt.Sprintf("%.3fms", ms)
	}
	if ms < 10 {
		return fmt.Sprintf("%.2fms", ms)
	}
	if ms < 100 {
		return fmt.Sprintf("%.1fms", ms)
	}
	return fmt.Sprintf("%.0fms", ms)
}

func readCycleStats(mem plcruntime.Memory) (last int64, longest int64, shortest int64, avg int64) {
	return 0, 0, -1, -1
}

func runDumpOnce() int {
	var runner plcruntime.Runner
	snapshot := &sharedMemory{}
	runner.Step()
	snapshot.Set(runner.Mem)
	tags := buildMemoryTagIndex(reflect.TypeOf(plcruntime.Memory{}))
	m := newModel(snapshot, tags)
	fmt.Println(m.View())
	return 0
}

func runInteractive(opcuaPort int, opcuaAdvertiseHost string, scanPeriod time.Duration, snapshotPeriod time.Duration) error {
	snapshot := &sharedMemory{}
	state := newRuntimeState(snapshot, snapshotPeriod)
	tags := buildMemoryTagIndex(reflect.TypeOf(plcruntime.Memory{}))

	opcuaSrv, err := startOPCUAServer(snapshot, tags, nil, opcuaPort, opcuaAdvertiseHost)
	if err != nil {
		return err
	}
	if opcuaSrv != nil {
		defer func() {
			_ = opcuaSrv.Close()
		}()
	}

	done := make(chan struct{})
	defer close(done)

	go state.run(done, scanPeriod)

	p := tea.NewProgram(newModel(snapshot, tags), tea.WithAltScreen())
	_, err = p.Run()
	return err
}

func runHeadless(cycles int, duration time.Duration) int {
	var runner plcruntime.Runner
	if cycles <= 0 && duration <= 0 {
		return 0
	}
	start := time.Now()
	if cycles > 0 {
		for i := 0; i < cycles; i++ {
			runner.Step()
		}
		elapsed := time.Since(start)
		if elapsed > 0 {
			fmt.Printf("cycles %d, elapsed %s, cps %.0f\n", cycles, elapsed, float64(cycles)/elapsed.Seconds())
		}
		return 0
	}

	deadline := time.Now().Add(duration)
	n := 0
	for {
		runner.Step()
		n++
		if n&255 == 0 {
			if time.Now().After(deadline) {
				break
			}
		}
	}
	elapsed := time.Since(start)
	if elapsed > 0 {
		fmt.Printf("cycles %d, elapsed %s, cps %.0f\n", n, elapsed, float64(n)/elapsed.Seconds())
	}
	return 0
}

func main() {
	dumpOnce := flag.Bool("dump-once", false, "run one scan, print one TUI frame, and exit")
	opcuaPort := flag.Int("opcua-port", 4840, "OPC-UA server port (set 0 to disable)")
	opcuaAdvertiseHost := flag.String("opcua-advertise-host", opcuaDefaultHostName, "OPC-UA endpoint host advertised to clients")
	opcuaBindHost := flag.String("opcua-bind-host", "", "reserved for OPC-UA bind-host parity; current server library listens on all interfaces for the selected port")
	scanPeriod := flag.Duration("scan-period", 0, "delay between scan cycles (0 to run as fast as possible)")
	snapshotPeriod := flag.Duration("snapshot-period", 20*time.Millisecond, "how often to snapshot runtime memory for the TUI/OPC-UA (0 to snapshot every scan)")
	cycles := flag.Int("cycles", 0, "run N scan cycles headless and exit")
	duration := flag.Duration("duration", 0, "run headless for duration and exit")
	symbolMapPath := flag.String("symbol-map", "symbol_map.json", "path to generated symbol_map.json")
	flag.Parse()
	_ = opcuaBindHost

	if *dumpOnce {
		os.Exit(runDumpOnce())
	}
	if *cycles > 0 || *duration > 0 {
		os.Exit(runHeadless(*cycles, *duration))
	}
	if stdinHasDebugProtocolInput() {
		if err := runProtocol(*symbolMapPath, *opcuaPort, *opcuaAdvertiseHost, *scanPeriod, *snapshotPeriod); err != nil {
			fmt.Fprintln(os.Stderr, "plc-run:", err)
			os.Exit(1)
		}
		return
	}

	if err := runInteractive(*opcuaPort, *opcuaAdvertiseHost, *scanPeriod, *snapshotPeriod); err != nil {
		fmt.Fprintln(os.Stderr, "plc-run:", err)
		os.Exit(1)
	}
}
