// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package main

import (
	"context"
	"crypto/x509"
	"encoding/json"
	"encoding/pem"
	"fmt"
	"github.com/awcullen/opcua/client"
	"github.com/awcullen/opcua/ua"
	"math"
	"net"
	"os"
	"plc-autogen/runtime"
	"reflect"
	"strings"
	"testing"
	"time"
)

func TestBuildMemoryTagIndex(t *testing.T) {
	type sample struct {
		Top bool
		DB  struct {
			Inner int16
		}
		hidden bool
	}

	tags := buildMemoryTagIndex(reflect.TypeOf(sample{}))
	if len(tags) < 2 {
		t.Fatalf("buildMemoryTagIndex() len=%d, want >=2", len(tags))
	}
	var hasInner bool
	var hasTop bool
	for _, tag := range tags {
		if tag.Name == "DB.Inner" {
			hasInner = true
		}
		if tag.Name == "Top" {
			hasTop = true
		}
	}
	if !hasInner || !hasTop {
		t.Fatalf("missing expected tags in %+v", tags)
	}
}

func TestOPCUAStructJSONReadWrite(t *testing.T) {
	type sample struct {
		DB struct {
			BlockTypeReference uint8
			Percent            float32
			Nested             struct {
				Enabled  bool
				Level    int16
				Overflow float64
			}
		}
	}
	var mem sample
	mem.DB.BlockTypeReference = 5
	mem.DB.Percent = float32(math.NaN())
	mem.DB.Nested.Level = 2
	mem.DB.Nested.Overflow = math.Inf(1)

	dbValue := reflect.ValueOf(mem).FieldByName("DB")
	raw := readOPCUAStructJSON(dbValue)
	var payload map[string]any
	if err := json.Unmarshal([]byte(raw), &payload); err != nil {
		t.Fatalf("struct JSON %q did not unmarshal: %v", raw, err)
	}
	if got := payload["BlockTypeReference"]; fmt.Sprint(got) != "5" {
		t.Fatalf("BlockTypeReference JSON=%v, want 5 in %q", got, raw)
	}
	if got, ok := payload["Percent"]; !ok || got != nil {
		t.Fatalf("Percent JSON=%v, want null in %q", got, raw)
	}
	nested, ok := payload["Nested"].(map[string]any)
	if !ok {
		t.Fatalf("Nested JSON=%T, want object in %q", payload["Nested"], raw)
	}
	if got := nested["Level"]; fmt.Sprint(got) != "2" {
		t.Fatalf("Nested.Level JSON=%v, want 2 in %q", got, raw)
	}
	if got, ok := nested["Overflow"]; !ok || got != nil {
		t.Fatalf("Nested.Overflow JSON=%v, want null in %q", got, raw)
	}

	target := reflect.ValueOf(&mem).Elem().FieldByName("DB")
	if status := setReflectValue(target, `{"BlockTypeReference":7,"Percent":3.5,"Nested":{"Enabled":true,"Level":12,"Overflow":4.5}}`); !status.IsGood() {
		t.Fatalf("setReflectValue struct JSON status=%v, want Good", status)
	}
	if mem.DB.BlockTypeReference != 7 || mem.DB.Percent != 3.5 || !mem.DB.Nested.Enabled || mem.DB.Nested.Level != 12 || mem.DB.Nested.Overflow != 4.5 {
		t.Fatalf("struct JSON write did not update memory: %+v", mem.DB)
	}
}

func TestOPCUAEndpointURLFormatsIPv6Host(t *testing.T) {
	got := opcuaEndpointURL("::1", 4840)
	want := "opc.tcp://[::1]:4840"
	if got != want {
		t.Fatalf("opcuaEndpointURL()=%q, want %q", got, want)
	}
}

func TestOPCUASelfSignedCertIncludesAdvertisedSANs(t *testing.T) {
	appURI := opcuaApplicationURI()

	t.Run("DNS host", func(t *testing.T) {
		certPath, _, cleanup, err := writeOPCUASelfSignedCert("plc.example.local", appURI)
		if err != nil {
			t.Fatalf("writeOPCUASelfSignedCert() error: %v", err)
		}
		defer cleanup()
		cert := readOPCUATestCertificate(t, certPath)
		if !opcuaTestHasDNS(cert.DNSNames, "localhost") || !opcuaTestHasDNS(cert.DNSNames, "plc.example.local") {
			t.Fatalf("DNSNames=%v, want localhost and advertised host", cert.DNSNames)
		}
		if !opcuaTestHasIP(cert.IPAddresses, "127.0.0.1") {
			t.Fatalf("IPAddresses=%v, want 127.0.0.1", cert.IPAddresses)
		}
		if !opcuaTestHasURI(cert, appURI) {
			t.Fatalf("URIs=%v, want %s", cert.URIs, appURI)
		}
	})

	t.Run("IP host", func(t *testing.T) {
		certPath, _, cleanup, err := writeOPCUASelfSignedCert("::1", appURI)
		if err != nil {
			t.Fatalf("writeOPCUASelfSignedCert() error: %v", err)
		}
		defer cleanup()
		cert := readOPCUATestCertificate(t, certPath)
		if !opcuaTestHasIP(cert.IPAddresses, "127.0.0.1") || !opcuaTestHasIP(cert.IPAddresses, "::1") {
			t.Fatalf("IPAddresses=%v, want loopback and advertised IPv6", cert.IPAddresses)
		}
		if !opcuaTestHasURI(cert, appURI) {
			t.Fatalf("URIs=%v, want %s", cert.URIs, appURI)
		}
	})
}

func readOPCUATestCertificate(t *testing.T, certPath string) *x509.Certificate {
	t.Helper()
	data, err := os.ReadFile(certPath)
	if err != nil {
		t.Fatalf("ReadFile(%s) error: %v", certPath, err)
	}
	block, _ := pem.Decode(data)
	if block == nil {
		t.Fatalf("certificate %s did not contain a PEM block", certPath)
	}
	cert, err := x509.ParseCertificate(block.Bytes)
	if err != nil {
		t.Fatalf("ParseCertificate(%s) error: %v", certPath, err)
	}
	return cert
}

func opcuaTestHasDNS(values []string, want string) bool {
	for _, value := range values {
		if strings.EqualFold(value, want) {
			return true
		}
	}
	return false
}

func opcuaTestHasIP(values []net.IP, want string) bool {
	ip := net.ParseIP(want)
	if ip == nil {
		return false
	}
	for _, value := range values {
		if value != nil && value.Equal(ip) {
			return true
		}
	}
	return false
}

func opcuaTestHasURI(cert *x509.Certificate, want string) bool {
	for _, value := range cert.URIs {
		if value != nil && value.String() == want {
			return true
		}
	}
	return false
}

func TestTUISearchRendering(t *testing.T) {
	m := model{
		tags:   []memoryTag{{Name: "DB_Main.Counter"}, {Name: "System.Flag"}},
		values: []string{"1", "true"},
		height: 20,
		width:  80,
	}
	m.applyFilter()
	m.query = "db"
	m.applyFilter()
	view := m.View()
	if !strings.Contains(strings.ToLower(view), "db_main.counter") {
		t.Fatalf("view missing filtered tag: %q", view)
	}
	if strings.Contains(strings.ToLower(view), "system.flag") {
		t.Fatalf("view still contains non-matching tag: %q", view)
	}
}

func TestOPCUAServer_AnonymousBrowseRead(t *testing.T) {

	snapshot := &sharedMemory{}
	state := newRuntimeState(snapshot, 0)
	state.Step()

	tags := buildMemoryTagIndex(reflect.TypeOf(plcruntime.Memory{}))
	if len(tags) == 0 {
		t.Skip("generated memory has no scalar tags")
	}

	port := freeTCPPort(t)
	srv, err := startOPCUAServer(snapshot, tags, nil, port, opcuaDefaultHostName)
	if err != nil {
		t.Fatalf("startOPCUAServer() error: %v", err)
	}
	defer func() {
		_ = srv.Close()
	}()

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	endpoint := fmt.Sprintf("opc.tcp://127.0.0.1:%d", port)
	ch, err := dialOPCUATestClient(ctx, endpoint)
	if err != nil {
		t.Fatalf("Dial() error: %v", err)
	}
	defer func() {
		_ = ch.Close(ctx)
	}()

	browseResp, err := ch.Browse(ctx, &ua.BrowseRequest{
		NodesToBrowse: []ua.BrowseDescription{{
			NodeID:          ua.ParseNodeID("ns=3;s=" + opcuaRootNodeID),
			BrowseDirection: ua.BrowseDirectionForward,
			ReferenceTypeID: ua.ReferenceTypeIDHasComponent,
			IncludeSubtypes: true,
			ResultMask:      uint32(ua.BrowseResultMaskAll),
		}},
	})
	if err != nil {
		t.Fatalf("Browse() error: %v", err)
	}
	if len(browseResp.Results) != 1 {
		t.Fatalf("Browse() results=%d, want 1", len(browseResp.Results))
	}
	if !browseResp.Results[0].StatusCode.IsGood() {
		t.Fatalf("Browse() status=%v, want Good", browseResp.Results[0].StatusCode)
	}
	if len(browseResp.Results[0].References) == 0 {
		t.Fatal("Browse() returned no PLC object references")
	}

	treeTag := tags[0]
	for _, tag := range tags {
		if len(tag.Parents) > 0 && !tag.Structured {
			treeTag = tag
			break
		}
	}
	if !strings.Contains(treeTag.NodeID, "\"") {
		t.Fatalf("tag node id %q does not use Siemens quoted path syntax", treeTag.NodeID)
	}
	if strings.Contains(treeTag.NodeID, "PLC.Memory") {
		t.Fatalf("tag node id %q still uses legacy PLC.Memory prefix", treeTag.NodeID)
	}
	for _, parent := range treeTag.Parents {
		assertOPCUAChildReference(t, ctx, ch, parent.ParentNodeID, parent.ReferenceKind, parent.NodeID, parent.BrowseName)
	}
	assertOPCUAChildReference(t, ctx, ch, treeTag.ParentNodeID, treeTag.ParentReferenceKind, treeTag.NodeID, treeTag.BrowseName)

	target := ua.ParseNodeID("ns=3;s=" + treeTag.NodeID)
	readResp, err := ch.Read(ctx, &ua.ReadRequest{NodesToRead: []ua.ReadValueID{{NodeID: target, AttributeID: ua.AttributeIDValue}}})
	if err != nil {
		t.Fatalf("Read() error: %v", err)
	}
	if len(readResp.Results) != 1 {
		t.Fatalf("Read() results=%d, want 1", len(readResp.Results))
	}
	if !readResp.Results[0].StatusCode.IsGood() {
		t.Fatalf("Read() status=%v, want Good", readResp.Results[0].StatusCode)
	}
	if readResp.Results[0].Value == nil {
		t.Fatal("Read() returned nil value")
	}
	if len(treeTag.AliasNodeIDs) > 0 {
		aliasTarget := ua.ParseNodeID("ns=3;s=" + treeTag.AliasNodeIDs[0])
		aliasResp, err := ch.Read(ctx, &ua.ReadRequest{NodesToRead: []ua.ReadValueID{{NodeID: aliasTarget, AttributeID: ua.AttributeIDValue}}})
		if err != nil {
			t.Fatalf("Read() alias node error: %v", err)
		}
		if len(aliasResp.Results) != 1 || !aliasResp.Results[0].StatusCode.IsGood() {
			t.Fatalf("alias node %q status=%v, want Good", treeTag.AliasNodeIDs[0], aliasResp.Results)
		}
	}
	legacyResp, err := ch.Read(ctx, &ua.ReadRequest{NodesToRead: []ua.ReadValueID{{NodeID: ua.ParseNodeID("ns=3;s=PLC.Memory." + treeTag.GeneratedName), AttributeID: ua.AttributeIDValue}}})
	if err != nil {
		t.Fatalf("Read() legacy node error: %v", err)
	}
	if len(legacyResp.Results) != 1 || legacyResp.Results[0].StatusCode != ua.BadNodeIDUnknown {
		t.Fatalf("legacy PLC.Memory node status=%v, want %v", legacyResp.Results, ua.BadNodeIDUnknown)
	}

	accessResp, err := ch.Read(ctx, &ua.ReadRequest{NodesToRead: []ua.ReadValueID{{NodeID: target, AttributeID: ua.AttributeIDAccessLevel}}})
	if err != nil {
		t.Fatalf("Read() access level error: %v", err)
	}
	if len(accessResp.Results) != 1 {
		t.Fatalf("Read() access level results=%d, want 1", len(accessResp.Results))
	}
	accessLevel, ok := accessResp.Results[0].Value.(byte)
	if !ok {
		t.Fatalf("AccessLevel value type=%T, want byte", accessResp.Results[0].Value)
	}
	if accessLevel&(ua.AccessLevelsCurrentRead|ua.AccessLevelsCurrentWrite) != (ua.AccessLevelsCurrentRead | ua.AccessLevelsCurrentWrite) {
		t.Skipf("generated runtime OPC memory nodes are read-only in this build (access level=%#x)", accessLevel)
	}
}

func assertOPCUAChildReference(t *testing.T, ctx context.Context, ch *client.Client, parentID string, referenceKind string, childID string, childBrowseName string) {
	t.Helper()
	parent := ua.ParseNodeID("ns=3;s=" + parentID)
	if parent == nil {
		t.Fatalf("invalid parent node id %q", parentID)
	}
	child := "ns=3;s=" + childID
	resp, err := ch.Browse(ctx, &ua.BrowseRequest{NodesToBrowse: []ua.BrowseDescription{{
		NodeID:          parent,
		BrowseDirection: ua.BrowseDirectionForward,
		ReferenceTypeID: opcuaReferenceTypeForKind(3, referenceKind),
		IncludeSubtypes: true,
		ResultMask:      uint32(ua.BrowseResultMaskAll),
	}}})
	if err != nil {
		t.Fatalf("Browse(%s) error: %v", parentID, err)
	}
	if len(resp.Results) != 1 || !resp.Results[0].StatusCode.IsGood() {
		t.Fatalf("Browse(%s) status=%v, want Good", parentID, resp.Results)
	}
	for _, ref := range resp.Results[0].References {
		if fmt.Sprint(ref.NodeID.NodeID) == child && ref.BrowseName.Name == childBrowseName {
			return
		}
	}
	t.Fatalf("Browse(%s, %s) did not expose %s/%s: %+v", parentID, referenceKind, child, childBrowseName, resp.Results[0].References)
}

func TestOPCUAServer_AnonymousWriteValidation(t *testing.T) {

	snapshot := &sharedMemory{}
	newRuntimeState(snapshot, 0)

	tags := buildMemoryTagIndex(reflect.TypeOf(plcruntime.Memory{}))
	tag, goodValue, badTypeValue, badRangeValue, ok := findWritableScalarTag(reflect.TypeOf(plcruntime.Memory{}), tags)
	if !ok {
		t.Skip("generated memory has no writable scalar tags suitable for validation")
	}
	port := freeTCPPort(t)
	srv, err := startOPCUAServer(snapshot, tags, nil, port, opcuaDefaultHostName)
	if err != nil {
		t.Fatalf("startOPCUAServer() error: %v", err)
	}
	defer func() {
		_ = srv.Close()
	}()

	ctx, cancel := context.WithTimeout(context.Background(), 5*time.Second)
	defer cancel()

	endpoint := fmt.Sprintf("opc.tcp://127.0.0.1:%d", port)
	ch, err := dialOPCUATestClient(ctx, endpoint)
	if err != nil {
		t.Fatalf("Dial() error: %v", err)
	}
	defer func() {
		_ = ch.Close(ctx)
	}()

	target := ua.ParseNodeID("ns=3;s=" + tag.NodeID)
	writeResp, err := ch.Write(ctx, &ua.WriteRequest{NodesToWrite: []ua.WriteValue{{
		NodeID:      target,
		AttributeID: ua.AttributeIDValue,
		Value:       ua.NewDataValue(goodValue, 0, time.Time{}, 0, time.Time{}, 0),
	}}})
	if err != nil {
		t.Skipf("generated runtime OPC writes unavailable in this build: %v", err)
	}
	if len(writeResp.Results) != 1 {
		t.Fatalf("Write() good value results=%v", writeResp.Results)
	}
	if writeResp.Results[0] == ua.BadUserAccessDenied || writeResp.Results[0] == ua.BadNotWritable {
		t.Skipf("generated runtime OPC writes unavailable in this build: %v", writeResp.Results[0])
	}
	if !writeResp.Results[0].IsGood() {
		t.Fatalf("Write() good value status=%v", writeResp.Results)
	}
	if got := readOPCUATagValueAt(snapshot, tag.Index); fmt.Sprint(got) != fmt.Sprint(goodValue) {
		t.Fatalf("live memory value=%v, want %v", got, goodValue)
	}

	readResp, err := ch.Read(ctx, &ua.ReadRequest{NodesToRead: []ua.ReadValueID{{NodeID: target, AttributeID: ua.AttributeIDValue}}})
	if err != nil {
		t.Fatalf("Read() after write error: %v", err)
	}
	if len(readResp.Results) != 1 || !readResp.Results[0].StatusCode.IsGood() {
		t.Fatalf("Read() after write status=%v", readResp.Results)
	}
	if fmt.Sprint(readResp.Results[0].Value) != fmt.Sprint(goodValue) {
		t.Fatalf("OPC readback=%v, want %v", readResp.Results[0].Value, goodValue)
	}

	typeResp, err := ch.Write(ctx, &ua.WriteRequest{NodesToWrite: []ua.WriteValue{{
		NodeID:      target,
		AttributeID: ua.AttributeIDValue,
		Value:       ua.NewDataValue(badTypeValue, 0, time.Time{}, 0, time.Time{}, 0),
	}}})
	if err != nil {
		t.Fatalf("Write() bad type error: %v", err)
	}
	if len(typeResp.Results) != 1 || typeResp.Results[0] != ua.BadTypeMismatch {
		t.Fatalf("Write() bad type status=%v, want %v", typeResp.Results, ua.BadTypeMismatch)
	}

	if badRangeValue != nil {
		rangeResp, err := ch.Write(ctx, &ua.WriteRequest{NodesToWrite: []ua.WriteValue{{
			NodeID:      target,
			AttributeID: ua.AttributeIDValue,
			Value:       ua.NewDataValue(badRangeValue, 0, time.Time{}, 0, time.Time{}, 0),
		}}})
		if err != nil {
			t.Fatalf("Write() bad range error: %v", err)
		}
		if len(rangeResp.Results) != 1 || (rangeResp.Results[0] != ua.BadOutOfRange && rangeResp.Results[0] != ua.BadTypeMismatch) {
			t.Fatalf("Write() bad range status=%v, want %v or %v", rangeResp.Results, ua.BadOutOfRange, ua.BadTypeMismatch)
		}
	}
}

func findWritableScalarTag(memType reflect.Type, tags []memoryTag) (memoryTag, any, any, any, bool) {
	for _, tag := range tags {
		if len(tag.Index) == 0 {
			continue
		}
		field := memType.FieldByIndex(tag.Index)
		switch field.Type.Kind() {
		case reflect.Bool:
			return tag, true, "bad", nil, true
		case reflect.Int8:
			return tag, int8(7), "bad", int16(1000), true
		case reflect.Int16:
			return tag, int16(7), "bad", int32(40000), true
		case reflect.Int32:
			return tag, int32(7), "bad", int64(1 << 40), true
		case reflect.Int, reflect.Int64:
			return tag, reflect.ValueOf(int64(7)).Convert(field.Type).Interface(), "bad", nil, true
		case reflect.Uint8:
			return tag, uint8(7), "bad", int16(-1), true
		case reflect.Uint16:
			return tag, uint16(7), "bad", int32(-1), true
		case reflect.Uint32:
			return tag, uint32(7), "bad", int64(-1), true
		case reflect.Uint, reflect.Uint64, reflect.Uintptr:
			return tag, reflect.ValueOf(uint64(7)).Convert(field.Type).Interface(), "bad", int16(-1), true
		case reflect.Float32:
			return tag, float32(7.5), "bad", nil, true
		case reflect.Float64:
			return tag, float64(7.5), "bad", nil, true
		case reflect.String:
			return tag, "written", int16(7), nil, true
		}
	}
	return memoryTag{}, nil, nil, nil, false
}

func dialOPCUATestClient(ctx context.Context, endpoint string) (*client.Client, error) {
	var lastErr error
	for attempt := 0; attempt < 20; attempt++ {
		ch, err := client.Dial(ctx, endpoint, client.WithInsecureSkipVerify())
		if err == nil {
			return ch, nil
		}
		lastErr = err
		select {
		case <-ctx.Done():
			return nil, ctx.Err()
		case <-time.After(100 * time.Millisecond):
		}
	}
	return nil, fmt.Errorf("dial OPC-UA endpoint %s failed: %w", endpoint, lastErr)
}

func freeTCPPort(t *testing.T) int {
	t.Helper()
	ln, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("net.Listen() error: %v", err)
	}
	defer ln.Close()
	addr, ok := ln.Addr().(*net.TCPAddr)
	if !ok {
		t.Fatalf("unexpected listener address type %T", ln.Addr())
	}
	return addr.Port
}
