// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package plcruntime

//line e:/VS/VS_Project/Porta_SCL_Viewer/Example/MotorControl.scl:1:1
func FB_MotorControl(mem *Memory, db *DB_MotorControl) {
//line e:/VS/VS_Project/Porta_SCL_Viewer/Example/MotorControl.scl:17:5
	db.v_statRun = ((db.v_Start || db.v_statRun) && !(db.v_Stop))
//line e:/VS/VS_Project/Porta_SCL_Viewer/Example/MotorControl.scl:18:5
	db.v_Run = db.v_statRun
}

//line e:/VS/VS_Project/Porta_SCL_Viewer/Example/MotorControl.s7dcl:1:1
func FB_MotorControl_S7DCL(mem *Memory, db *DB_MotorControl_S7DCL) {
	// (no statements)
}
