// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package plcruntime

type Memory struct {
	SCLH_CycleLastNS        int64
	SCLH_CycleLongestNS     int64
	SCLH_CycleShortestNS    int64
	SCLH_CycleWindowNS      int64
	SCLH_CycleWindowCount   int64
	SCLH_LastStepNS         int64
	scltestHarness_2a8723d3 DB_MotorControl `opcua:"kind=scltest&name=MotorControl&section=static&type=MotorControl"`
}

type DB_MotorControl struct {
	SCLH_InitDone bool
	v_Run         bool `opcua:"kind=field&name=Run&section=output&type=Bool"`
	v_Start       bool `opcua:"kind=field&name=Start&section=input&type=Bool"`
	v_statRun     bool `opcua:"kind=field&name=statRun&section=static&type=Bool"`
	v_Stop        bool `opcua:"kind=field&name=Stop&section=input&type=Bool"`
}

type DB_MotorControl_S7DCL struct {
	SCLH_InitDone bool
	v_Run         bool `opcua:"kind=field&name=Run&section=output&type=Bool"`
	v_Start       bool `opcua:"kind=field&name=Start&section=input&type=Bool"`
	v_statRun     bool `opcua:"kind=field&name=statRun&section=static&type=Bool"`
	v_Stop        bool `opcua:"kind=field&name=Stop&section=input&type=Bool"`
}
