// Code generated by siemens-lsp go-gen. DO NOT EDIT.

package plcruntime

import (
	"fmt"
	"testing"
)

type TestObservationHooks interface {
	OnTestStart(TestStartEvent)
	OnStep(TestStepEvent)
	OnAssert(TestAssertEvent)
	OnTestComplete(TestCompleteEvent)
}

type TestStartEvent struct {
	CaseName   string
	StableID   string
	SourcePath string
	Line       int
	Column     int
}

type TestStepEvent struct {
	CaseName   string
	StableID   string
	SourcePath string
	Line       int
	Column     int
	Step       int
	Kind       string
	ClockNow   TIME
}

type TestAssertEvent struct {
	CaseName   string
	StableID   string
	SourcePath string
	Line       int
	Column     int
	Step       int
	Kind       string
	Passed     bool
	Condition  string
	Operator   string
	Got        string
	Expected   string
	Tolerance  string
	ClockNow   TIME
}

type TestCompleteEvent struct {
	CaseName   string
	StableID   string
	SourcePath string
	Line       int
	Column     int
	Passed     bool
	Steps      int
	ClockNow   TIME
}

type TestRuntimeContext struct {
	Hooks  TestObservationHooks
	Runner *Runner
	Clock  *TestClock
}

func NewTestRuntimeContext(hooks TestObservationHooks) *TestRuntimeContext {
	clock := &TestClock{}
	runner := &Runner{Clock: clock}
	return &TestRuntimeContext{Hooks: hooks, Runner: runner, Clock: clock}
}

func observeTestStart(ctx *TestRuntimeContext, event TestStartEvent) {
	if ctx != nil && ctx.Hooks != nil {
		defer func() { _ = recover() }()
		ctx.Hooks.OnTestStart(event)
	}
}

func observeTestStep(ctx *TestRuntimeContext, event TestStepEvent) {
	if ctx != nil && ctx.Hooks != nil {
		defer func() { _ = recover() }()
		ctx.Hooks.OnStep(event)
	}
}

func observeTestAssert(ctx *TestRuntimeContext, event TestAssertEvent) {
	if ctx != nil && ctx.Hooks != nil {
		defer func() { _ = recover() }()
		ctx.Hooks.OnAssert(event)
	}
}

func observeTestComplete(ctx *TestRuntimeContext, event TestCompleteEvent) {
	if ctx != nil && ctx.Hooks != nil {
		defer func() { _ = recover() }()
		ctx.Hooks.OnTestComplete(event)
	}
}

func testObservationString(value any) string {
	return fmt.Sprint(value)
}

func resetGeneratedTestBuiltinsState() {
}

func resetGeneratedTestRuntimeState() {
	resetGeneratedTestBuiltinsState()

}

func stepScltestHarness_2a8723d3(r *Runner) {
	FB_MotorControl(&r.Mem, &r.Mem.scltestHarness_2a8723d3)
}

func TestUserCase001_MotorStartsWhenStartIsPressed(t *testing.T) {
	t.Parallel()
	runTestUserCase001_MotorStartsWhenStartIsPressed(t, nil)
}

func runTestUserCase001_MotorStartsWhenStartIsPressed(t *testing.T, hooks TestObservationHooks) {
	type testHeldAssignment struct {
		key   string
		apply func()
	}
	ctx := NewTestRuntimeContext(hooks)
	runner := ctx.Runner
	clock := ctx.Clock
	mem := &runner.Mem
	_ = runner
	_ = mem
	heldAssignments := []testHeldAssignment{}
	applyHeldAssignments := func() {
		for _, hold := range heldAssignments {
			hold.apply()
		}
	}
	setHeldAssignment := func(key string, apply func()) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments[i].apply = apply
				return
			}
		}
		heldAssignments = append(heldAssignments, testHeldAssignment{key: key, apply: apply})
	}
	releaseHeldAssignment := func(key string) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments = append(heldAssignments[:i], heldAssignments[i+1:]...)
				return
			}
		}
	}
	clearHeldAssignments := func() {
		heldAssignments = heldAssignments[:0]
	}
	_ = applyHeldAssignments
	_ = setHeldAssignment
	_ = releaseHeldAssignment
	_ = clearHeldAssignments
	const waitCycleStep = TIME(1_000_000)
	const waitUntilPollStep = TIME(1_000_000)
	passed := false
	observeTestStart(ctx, TestStartEvent{CaseName: "Motor starts when Start is pressed", StableID: "scltest:MotorControl.scltest:L3:C1:Motor starts when Start is pressed", SourcePath: "MotorControl.scltest", Line: 3, Column: 1})
	defer observeTestComplete(ctx, TestCompleteEvent{CaseName: "Motor starts when Start is pressed", StableID: "scltest:MotorControl.scltest:L3:C1:Motor starts when Start is pressed", SourcePath: "MotorControl.scltest", Line: 3, Column: 1, Passed: passed, Steps: 4, ClockNow: clock.Now()})
	runner.testStep = stepScltestHarness_2a8723d3
	observeTestStep(ctx, TestStepEvent{CaseName: "Motor starts when Start is pressed", StableID: "scltest:MotorControl.scltest:L3:C1:Motor starts when Start is pressed", SourcePath: "MotorControl.scltest", Line: 4, Column: 5, Step: 1, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.scltestHarness_2a8723d3.v_Start = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "Motor starts when Start is pressed", StableID: "scltest:MotorControl.scltest:L3:C1:Motor starts when Start is pressed", SourcePath: "MotorControl.scltest", Line: 5, Column: 5, Step: 2, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.scltestHarness_2a8723d3.v_Stop = false
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "Motor starts when Start is pressed", StableID: "scltest:MotorControl.scltest:L3:C1:Motor starts when Start is pressed", SourcePath: "MotorControl.scltest", Line: 6, Column: 5, Step: 3, Kind: "WAIT_CYCLES", ClockNow: clock.Now()})
	{
		steps := int(1)
		if steps < 0 {
			steps = 0
		}
		for i := 0; i < steps; i++ {
			clock.Advance(waitCycleStep)
			applyHeldAssignments()
			runner.Step()
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "Motor starts when Start is pressed", StableID: "scltest:MotorControl.scltest:L3:C1:Motor starts when Start is pressed", SourcePath: "MotorControl.scltest", Line: 7, Column: 5, Step: 4, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.scltestHarness_2a8723d3.v_Run
		expectedValue := true
		assertPassed := (mem.scltestHarness_2a8723d3.v_Run == true)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "Motor starts when Start is pressed", StableID: "scltest:MotorControl.scltest:L3:C1:Motor starts when Start is pressed", SourcePath: "MotorControl.scltest", Line: 7, Column: 5, Step: 4, Kind: "ASSERT", Passed: assertPassed, Condition: "UUT.Run = TRUE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at MotorControl.scltest:7:5 step 4: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	passed = true
}

func TestUserCase002_MotorHoldsRunStateWhenStartIsReleased(t *testing.T) {
	t.Parallel()
	runTestUserCase002_MotorHoldsRunStateWhenStartIsReleased(t, nil)
}

func runTestUserCase002_MotorHoldsRunStateWhenStartIsReleased(t *testing.T, hooks TestObservationHooks) {
	type testHeldAssignment struct {
		key   string
		apply func()
	}
	ctx := NewTestRuntimeContext(hooks)
	runner := ctx.Runner
	clock := ctx.Clock
	mem := &runner.Mem
	_ = runner
	_ = mem
	heldAssignments := []testHeldAssignment{}
	applyHeldAssignments := func() {
		for _, hold := range heldAssignments {
			hold.apply()
		}
	}
	setHeldAssignment := func(key string, apply func()) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments[i].apply = apply
				return
			}
		}
		heldAssignments = append(heldAssignments, testHeldAssignment{key: key, apply: apply})
	}
	releaseHeldAssignment := func(key string) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments = append(heldAssignments[:i], heldAssignments[i+1:]...)
				return
			}
		}
	}
	clearHeldAssignments := func() {
		heldAssignments = heldAssignments[:0]
	}
	_ = applyHeldAssignments
	_ = setHeldAssignment
	_ = releaseHeldAssignment
	_ = clearHeldAssignments
	const waitCycleStep = TIME(1_000_000)
	const waitUntilPollStep = TIME(1_000_000)
	passed := false
	observeTestStart(ctx, TestStartEvent{CaseName: "Motor holds run state when Start is released", StableID: "scltest:MotorControl.scltest:L10:C1:Motor holds run state when Start is released", SourcePath: "MotorControl.scltest", Line: 10, Column: 1})
	defer observeTestComplete(ctx, TestCompleteEvent{CaseName: "Motor holds run state when Start is released", StableID: "scltest:MotorControl.scltest:L10:C1:Motor holds run state when Start is released", SourcePath: "MotorControl.scltest", Line: 10, Column: 1, Passed: passed, Steps: 7, ClockNow: clock.Now()})
	runner.testStep = stepScltestHarness_2a8723d3
	observeTestStep(ctx, TestStepEvent{CaseName: "Motor holds run state when Start is released", StableID: "scltest:MotorControl.scltest:L10:C1:Motor holds run state when Start is released", SourcePath: "MotorControl.scltest", Line: 12, Column: 5, Step: 1, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.scltestHarness_2a8723d3.v_Start = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "Motor holds run state when Start is released", StableID: "scltest:MotorControl.scltest:L10:C1:Motor holds run state when Start is released", SourcePath: "MotorControl.scltest", Line: 13, Column: 5, Step: 2, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.scltestHarness_2a8723d3.v_Stop = false
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "Motor holds run state when Start is released", StableID: "scltest:MotorControl.scltest:L10:C1:Motor holds run state when Start is released", SourcePath: "MotorControl.scltest", Line: 14, Column: 5, Step: 3, Kind: "WAIT_CYCLES", ClockNow: clock.Now()})
	{
		steps := int(1)
		if steps < 0 {
			steps = 0
		}
		for i := 0; i < steps; i++ {
			clock.Advance(waitCycleStep)
			applyHeldAssignments()
			runner.Step()
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "Motor holds run state when Start is released", StableID: "scltest:MotorControl.scltest:L10:C1:Motor holds run state when Start is released", SourcePath: "MotorControl.scltest", Line: 15, Column: 5, Step: 4, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.scltestHarness_2a8723d3.v_Run
		expectedValue := true
		assertPassed := (mem.scltestHarness_2a8723d3.v_Run == true)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "Motor holds run state when Start is released", StableID: "scltest:MotorControl.scltest:L10:C1:Motor holds run state when Start is released", SourcePath: "MotorControl.scltest", Line: 15, Column: 5, Step: 4, Kind: "ASSERT", Passed: assertPassed, Condition: "UUT.Run = TRUE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at MotorControl.scltest:15:5 step 4: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "Motor holds run state when Start is released", StableID: "scltest:MotorControl.scltest:L10:C1:Motor holds run state when Start is released", SourcePath: "MotorControl.scltest", Line: 18, Column: 5, Step: 5, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.scltestHarness_2a8723d3.v_Start = false
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "Motor holds run state when Start is released", StableID: "scltest:MotorControl.scltest:L10:C1:Motor holds run state when Start is released", SourcePath: "MotorControl.scltest", Line: 19, Column: 5, Step: 6, Kind: "WAIT_CYCLES", ClockNow: clock.Now()})
	{
		steps := int(1)
		if steps < 0 {
			steps = 0
		}
		for i := 0; i < steps; i++ {
			clock.Advance(waitCycleStep)
			applyHeldAssignments()
			runner.Step()
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "Motor holds run state when Start is released", StableID: "scltest:MotorControl.scltest:L10:C1:Motor holds run state when Start is released", SourcePath: "MotorControl.scltest", Line: 20, Column: 5, Step: 7, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.scltestHarness_2a8723d3.v_Run
		expectedValue := true
		assertPassed := (mem.scltestHarness_2a8723d3.v_Run == true)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "Motor holds run state when Start is released", StableID: "scltest:MotorControl.scltest:L10:C1:Motor holds run state when Start is released", SourcePath: "MotorControl.scltest", Line: 20, Column: 5, Step: 7, Kind: "ASSERT", Passed: assertPassed, Condition: "UUT.Run = TRUE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at MotorControl.scltest:20:5 step 7: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	passed = true
}

func TestUserCase003_MotorStopsWhenStopIsPressed(t *testing.T) {
	t.Parallel()
	runTestUserCase003_MotorStopsWhenStopIsPressed(t, nil)
}

func runTestUserCase003_MotorStopsWhenStopIsPressed(t *testing.T, hooks TestObservationHooks) {
	type testHeldAssignment struct {
		key   string
		apply func()
	}
	ctx := NewTestRuntimeContext(hooks)
	runner := ctx.Runner
	clock := ctx.Clock
	mem := &runner.Mem
	_ = runner
	_ = mem
	heldAssignments := []testHeldAssignment{}
	applyHeldAssignments := func() {
		for _, hold := range heldAssignments {
			hold.apply()
		}
	}
	setHeldAssignment := func(key string, apply func()) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments[i].apply = apply
				return
			}
		}
		heldAssignments = append(heldAssignments, testHeldAssignment{key: key, apply: apply})
	}
	releaseHeldAssignment := func(key string) {
		for i := range heldAssignments {
			if heldAssignments[i].key == key {
				heldAssignments = append(heldAssignments[:i], heldAssignments[i+1:]...)
				return
			}
		}
	}
	clearHeldAssignments := func() {
		heldAssignments = heldAssignments[:0]
	}
	_ = applyHeldAssignments
	_ = setHeldAssignment
	_ = releaseHeldAssignment
	_ = clearHeldAssignments
	const waitCycleStep = TIME(1_000_000)
	const waitUntilPollStep = TIME(1_000_000)
	passed := false
	observeTestStart(ctx, TestStartEvent{CaseName: "Motor stops when Stop is pressed", StableID: "scltest:MotorControl.scltest:L23:C1:Motor stops when Stop is pressed", SourcePath: "MotorControl.scltest", Line: 23, Column: 1})
	defer observeTestComplete(ctx, TestCompleteEvent{CaseName: "Motor stops when Stop is pressed", StableID: "scltest:MotorControl.scltest:L23:C1:Motor stops when Stop is pressed", SourcePath: "MotorControl.scltest", Line: 23, Column: 1, Passed: passed, Steps: 7, ClockNow: clock.Now()})
	runner.testStep = stepScltestHarness_2a8723d3
	observeTestStep(ctx, TestStepEvent{CaseName: "Motor stops when Stop is pressed", StableID: "scltest:MotorControl.scltest:L23:C1:Motor stops when Stop is pressed", SourcePath: "MotorControl.scltest", Line: 25, Column: 5, Step: 1, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.scltestHarness_2a8723d3.v_Start = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "Motor stops when Stop is pressed", StableID: "scltest:MotorControl.scltest:L23:C1:Motor stops when Stop is pressed", SourcePath: "MotorControl.scltest", Line: 26, Column: 5, Step: 2, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.scltestHarness_2a8723d3.v_Stop = false
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "Motor stops when Stop is pressed", StableID: "scltest:MotorControl.scltest:L23:C1:Motor stops when Stop is pressed", SourcePath: "MotorControl.scltest", Line: 27, Column: 5, Step: 3, Kind: "WAIT_CYCLES", ClockNow: clock.Now()})
	{
		steps := int(1)
		if steps < 0 {
			steps = 0
		}
		for i := 0; i < steps; i++ {
			clock.Advance(waitCycleStep)
			applyHeldAssignments()
			runner.Step()
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "Motor stops when Stop is pressed", StableID: "scltest:MotorControl.scltest:L23:C1:Motor stops when Stop is pressed", SourcePath: "MotorControl.scltest", Line: 28, Column: 5, Step: 4, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.scltestHarness_2a8723d3.v_Run
		expectedValue := true
		assertPassed := (mem.scltestHarness_2a8723d3.v_Run == true)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "Motor stops when Stop is pressed", StableID: "scltest:MotorControl.scltest:L23:C1:Motor stops when Stop is pressed", SourcePath: "MotorControl.scltest", Line: 28, Column: 5, Step: 4, Kind: "ASSERT", Passed: assertPassed, Condition: "UUT.Run = TRUE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at MotorControl.scltest:28:5 step 4: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "Motor stops when Stop is pressed", StableID: "scltest:MotorControl.scltest:L23:C1:Motor stops when Stop is pressed", SourcePath: "MotorControl.scltest", Line: 31, Column: 5, Step: 5, Kind: "SET", ClockNow: clock.Now()})
	{
		mem.scltestHarness_2a8723d3.v_Stop = true
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "Motor stops when Stop is pressed", StableID: "scltest:MotorControl.scltest:L23:C1:Motor stops when Stop is pressed", SourcePath: "MotorControl.scltest", Line: 32, Column: 5, Step: 6, Kind: "WAIT_CYCLES", ClockNow: clock.Now()})
	{
		steps := int(1)
		if steps < 0 {
			steps = 0
		}
		for i := 0; i < steps; i++ {
			clock.Advance(waitCycleStep)
			applyHeldAssignments()
			runner.Step()
		}
	}
	observeTestStep(ctx, TestStepEvent{CaseName: "Motor stops when Stop is pressed", StableID: "scltest:MotorControl.scltest:L23:C1:Motor stops when Stop is pressed", SourcePath: "MotorControl.scltest", Line: 33, Column: 5, Step: 7, Kind: "ASSERT", ClockNow: clock.Now()})
	{
		gotValue := mem.scltestHarness_2a8723d3.v_Run
		expectedValue := false
		assertPassed := (mem.scltestHarness_2a8723d3.v_Run == false)
		observeTestAssert(ctx, TestAssertEvent{CaseName: "Motor stops when Stop is pressed", StableID: "scltest:MotorControl.scltest:L23:C1:Motor stops when Stop is pressed", SourcePath: "MotorControl.scltest", Line: 33, Column: 5, Step: 7, Kind: "ASSERT", Passed: assertPassed, Condition: "UUT.Run = FALSE", Operator: "=", Got: testObservationString(gotValue), Expected: testObservationString(expectedValue), ClockNow: clock.Now()})
		if !assertPassed {
			t.Fatalf("ASSERT failed at MotorControl.scltest:33:5 step 7: got=%v op== expected=%v", gotValue, expectedValue)
		}
	}
	passed = true
}
